/**
 * Dicionário de correção de encoding para municípios brasileiros.
 * Gerado automaticamente a partir de dados IBGE.
 * Mapeia nomes com U+FFFD (encoding quebrado) → nomes corretos com acentos.
 */

const R = '\uFFFD';

export const MUNICIPIOS_DICT: Record<string, string> = {
  "Abadia de Goi�s": "Abadia de Goiás",
  "Abadi�nia": "Abadiânia",
  "Abaet�": "Abaeté",
  "Aba�ra": "Abaíra",
  "Abar�": "Abaré",
  "Abati�": "Abatiá",
  "Abreul�ndia": "Abreulândia",
  "A�ail�ndia": "Açailândia",
  "Acar�": "Acará",
  "Acara�": "Acaraú",
  "Acau�": "Acauã",
  "Acegu�": "Aceguá",
  "Acrel�ndia": "Acrelândia",
  "Acre�na": "Acreúna",
  "A�u": "Açu",
  "A�ucena": "Açucena",
  "Adel�ndia": "Adelândia",
  "Adrian�polis": "Adrianópolis",
  "Afonso Cl�udio": "Afonso Cláudio",
  "Afr�nio": "Afrânio",
  "Afu�": "Afuá",
  "Agricol�ndia": "Agricolândia",
  "Agrol�ndia": "Agrolândia",
  "Agron�mica": "Agronômica",
  "�gua Azul do Norte": "Água Azul do Norte",
  "�gua Boa": "Água Boa",
  "�gua Branca": "Água Branca",
  "�gua Clara": "Água Clara",
  "�gua Comprida": "Água Comprida",
  "�gua Doce": "Água Doce",
  "�gua Doce do Maranh�o": "Água Doce do Maranhão",
  "�gua Doce do Norte": "Água Doce do Norte",
  "�gua Fria": "Água Fria",
  "�gua Fria de Goi�s": "Água Fria de Goiás",
  "�gua Limpa": "Água Limpa",
  "�gua Nova": "Água Nova",
  "�gua Preta": "Água Preta",
  "�gua Santa": "Água Santa",
  "Agua�": "Aguaí",
  "�guas Belas": "Águas Belas",
  "�guas da Prata": "Águas da Prata",
  "�guas de Chapec�": "Águas de Chapecó",
  "�guas de Lind�ia": "Águas de Lindóia",
  "�guas de Santa B�rbara": "Águas de Santa Bárbara",
  "�guas de S�o Pedro": "Águas de São Pedro",
  "�guas Formosas": "Águas Formosas",
  "�guas Frias": "Águas Frias",
  "�guas Lindas de Goi�s": "Águas Lindas de Goiás",
  "�guas Mornas": "Águas Mornas",
  "�guas Vermelhas": "Águas Vermelhas",
  "�guia Branca": "Águia Branca",
  "Aguiarn�polis": "Aguiarnópolis",
  "Aimor�s": "Aimorés",
  "Alagoinha do Piau�": "Alagoinha do Piauí",
  "Alc�ntara": "Alcântara",
  "Alc�ntaras": "Alcântaras",
  "Alcin�polis": "Alcinópolis",
  "Alcoba�a": "Alcobaça",
  "Alegrete do Piau�": "Alegrete do Piauí",
  "Al�m Para�ba": "Além Paraíba",
  "Alex�nia": "Alexânia",
  "Algod�o de Janda�ra": "Algodão de Jandaíra",
  "Alian�a": "Aliança",
  "Alian�a do Tocantins": "Aliança do Tocantins",
  "Almirante Tamandar�": "Almirante Tamandaré",
  "Almirante Tamandar� do Sul": "Almirante Tamandaré do Sul",
  "Alo�ndia": "Aloândia",
  "Alpin�polis": "Alpinópolis",
  "Altamira do Maranh�o": "Altamira do Maranhão",
  "Altamira do Paran�": "Altamira do Paraná",
  "Altin�polis": "Altinópolis",
  "Alto Alegre do Maranh�o": "Alto Alegre do Maranhão",
  "Alto Alegre do Pindar�": "Alto Alegre do Pindaré",
  "Alto Capara�": "Alto Caparaó",
  "Alto Gar�as": "Alto Garças",
  "Alto Jequitib�": "Alto Jequitibá",
  "Alto Long�": "Alto Longá",
  "Alto Para�so": "Alto Paraíso",
  "Alto Para�so de Goi�s": "Alto Paraíso de Goiás",
  "Alto Paran�": "Alto Paraná",
  "Alto Parna�ba": "Alto Parnaíba",
  "Alt�nia": "Altônia",
  "Alum�nio": "Alumínio",
  "Alvar�es": "Alvarães",
  "�lvares Florence": "Álvares Florence",
  "�lvares Machado": "Álvares Machado",
  "�lvaro de Carvalho": "Álvaro de Carvalho",
  "Alvinl�ndia": "Alvinlândia",
  "Alvin�polis": "Alvinópolis",
  "Alvorada do Gurgu�ia": "Alvorada do Gurguéia",
  "Amap�": "Amapá",
  "Amap� do Maranh�o": "Amapá do Maranhão",
  "Amapor�": "Amaporã",
  "Amarante do Maranh�o": "Amarante do Maranhão",
  "Amatur�": "Amaturá",
  "Am�lia Rodrigues": "Amélia Rodrigues",
  "Am�rica Dourada": "América Dourada",
  "Am�rico Brasiliense": "Américo Brasiliense",
  "Am�rico de Campos": "Américo de Campos",
  "Amorin�polis": "Amorinópolis",
  "Amparo de S�o Francisco": "Amparo de São Francisco",
  "Amp�re": "Ampére",
  "Anag�": "Anagé",
  "Anaj�s": "Anajás",
  "Anal�ndia": "Analândia",
  "Anam�": "Anamã",
  "Anan�s": "Ananás",
  "An�polis": "Anápolis",
  "Anast�cio": "Anastácio",
  "Anauril�ndia": "Anaurilândia",
  "Andara�": "Andaraí",
  "Andir�": "Andirá",
  "Andr� da Rocha": "André da Rocha",
  "Andrel�ndia": "Andrelândia",
  "Angel�ndia": "Angelândia",
  "Ang�lica": "Angélica",
  "Angical do Piau�": "Angical do Piauí",
  "�ngulo": "Ângulo",
  "An�sio de Abreu": "Anísio de Abreu",
  "Anit�polis": "Anitápolis",
  "Ant�nio Almeida": "Antônio Almeida",
  "Ant�nio Cardoso": "Antônio Cardoso",
  "Ant�nio Carlos": "Antônio Carlos",
  "Ant�nio Dias": "Antônio Dias",
  "Ant�nio Gon�alves": "Antônio Gonçalves",
  "Ant�nio Jo�o": "Antônio João",
  "Ant�nio Martins": "Antônio Martins",
  "Ant�nio Olinto": "Antônio Olinto",
  "Ant�nio Prado": "Antônio Prado",
  "Ant�nio Prado de Minas": "Antônio Prado de Minas",
  "Aparecida de Goi�nia": "Aparecida de Goiânia",
  "Aperib�": "Aperibé",
  "Apiac�": "Apiacá",
  "Apiac�s": "Apiacás",
  "Apia�": "Apiaí",
  "Apicum-A�u": "Apicum-Açu",
  "Api�na": "Apiúna",
  "Apor�": "Aporé",
  "Apu�": "Apuí",
  "Apuiar�s": "Apuiarés",
  "Aquidab�": "Aquidabã",
  "Arabut�": "Arabutã",
  "Ara�agi": "Araçagi",
  "Ara�a�": "Araçaí",
  "Ara�ariguama": "Araçariguama",
  "Ara�as": "Araças",
  "Ara�atuba": "Araçatuba",
  "Ara�oiaba": "Araçoiaba",
  "Ara�oiaba da Serra": "Araçoiaba da Serra",
  "Ara�u": "Araçu",
  "Ara�ua�": "Araçuaí",
  "Aragar�as": "Aragarças",
  "Aragoi�nia": "Aragoiânia",
  "Aragua�u": "Araguaçu",
  "Aragua�na": "Araguaína",
  "Araguan�": "Araguanã",
  "Arambar�": "Arambaré",
  "Arape�": "Arapeí",
  "Arapor�": "Araporã",
  "Arapu�": "Arapuã",
  "Ararangu�": "Araranguá",
  "Ararend�": "Ararendá",
  "Araric�": "Araricá",
  "Aratu�pe": "Aratuípe",
  "Arau�": "Arauá",
  "Arauc�ria": "Araucária",
  "Ara�jos": "Araújos",
  "Arax�": "Araxá",
  "Arco-�ris": "Arco-Íris",
  "Areia de Bara�nas": "Areia de Baraúnas",
  "Arei�polis": "Areiópolis",
  "Aren�polis": "Arenópolis",
  "Ar�s": "Arês",
  "Aripuan�": "Aripuanã",
  "Ariranha do Iva�": "Ariranha do Ivaí",
  "Arma��o dos B�zios": "Armação dos Búzios",
  "Armaz�m": "Armazém",
  "Aruan�": "Aruanã",
  "Aruj�": "Arujá",
  "Asp�sia": "Aspásia",
  "Assa�": "Assaí",
  "Assar�": "Assaré",
  "Assun��o": "Assunção",
  "Assun��o do Piau�": "Assunção do Piauí",
  "Atal�ia": "Ataléia",
  "Augustin�polis": "Augustinópolis",
  "Augusto Corr�a": "Augusto Corrêa",
  "�urea": "Áurea",
  "Auril�ndia": "Aurilândia",
  "Aurora do Par�": "Aurora do Pará",
  "Ava�": "Avaí",
  "Avar�": "Avaré",
  "Avelin�polis": "Avelinópolis",
  "Axix�": "Axixá",
  "Axix� do Tocantins": "Axixá do Tocantins",
  "Baba�ul�ndia": "Babaçulândia",
  "Bag�": "Bagé",
  "Ba�a da Trai��o": "Baía da Traição",
  "Ba�a Formosa": "Baía Formosa",
  "Baian�polis": "Baianópolis",
  "Bai�o": "Baião",
  "Balne�rio Arroio do Silva": "Balneário Arroio do Silva",
  "Balne�rio Barra do Sul": "Balneário Barra do Sul",
  "Balne�rio Cambori�": "Balneário Camboriú",
  "Balne�rio Gaivota": "Balneário Gaivota",
  "Balne�rio Pi�arras": "Balneário Piçarras",
  "Balne�rio Pinhal": "Balneário Pinhal",
  "Balne�rio Rinc�o": "Balneário Rincão",
  "B�lsamo": "Bálsamo",
  "Bambu�": "Bambuí",
  "Banabui�": "Banabuiú",
  "Banza�": "Banzaê",
  "Bar�o": "Barão",
  "Bar�o de Antonina": "Barão de Antonina",
  "Bar�o de Cocais": "Barão de Cocais",
  "Bar�o de Cotegipe": "Barão de Cotegipe",
  "Bar�o de Graja�": "Barão de Grajaú",
  "Bar�o de Melga�o": "Barão de Melgaço",
  "Bar�o de Monte Alto": "Barão de Monte Alto",
  "Bar�o do Triunfo": "Barão do Triunfo",
  "Bara�na": "Baraúna",
  "Barra D'Alc�ntara": "Barra D'Alcântara",
  "Barra de Santo Ant�nio": "Barra de Santo Antônio",
  "Barra de S�o Francisco": "Barra de São Francisco",
  "Barra de S�o Miguel": "Barra de São Miguel",
  "Barra do Chap�u": "Barra do Chapéu",
  "Barra do Cho�a": "Barra do Choça",
  "Barra do Gar�as": "Barra do Garças",
  "Barra do Jacar�": "Barra do Jacaré",
  "Barra do Pira�": "Barra do Piraí",
  "Barra do Quara�": "Barra do Quaraí",
  "Barrac�o": "Barracão",
  "Barreiras do Piau�": "Barreiras do Piauí",
  "Barrol�ndia": "Barrolândia",
  "Bataypor�": "Batayporã",
  "Baturit�": "Baturité",
  "Bela Vista de Goi�s": "Bela Vista de Goiás",
  "Bela Vista do Maranh�o": "Bela Vista do Maranhão",
  "Bela Vista do Para�so": "Bela Vista do Paraíso",
  "Bela Vista do Piau�": "Bela Vista do Piauí",
  "Bel�gua": "Belágua",
  "Bel�m": "Belém",
  "Bel�m de Maria": "Belém de Maria",
  "Bel�m do Brejo do Cruz": "Belém do Brejo do Cruz",
  "Bel�m do Piau�": "Belém do Piauí",
  "Bel�m do S�o Francisco": "Belém do São Francisco",
  "Bento Gon�alves": "Bento Gonçalves",
  "Bequim�o": "Bequimão",
  "Bernardo Say�o": "Bernardo Sayão",
  "Bertol�nia": "Bertolínia",
  "Bert�polis": "Bertópolis",
  "Bet�nia": "Betânia",
  "Bet�nia do Piau�": "Betânia do Piauí",
  "Bigua�u": "Biguaçu",
  "Boa Esperan�a": "Boa Esperança",
  "Boa Esperan�a do Igua�u": "Boa Esperança do Iguaçu",
  "Boa Esperan�a do Sul": "Boa Esperança do Sul",
  "Boa Ventura de S�o Roque": "Boa Ventura de São Roque",
  "Boa Vista das Miss�es": "Boa Vista das Missões",
  "Boa Vista do Buric�": "Boa Vista do Buricá",
  "Bocai�va": "Bocaiúva",
  "Bocai�va do Sul": "Bocaiúva do Sul",
  "Bod�": "Bodó",
  "Bodoc�": "Bodocó",
  "Bom Jardim de Goi�s": "Bom Jardim de Goiás",
  "Bom Jesus de Goi�s": "Bom Jesus de Goiás",
  "Bom Jesus dos Perd�es": "Bom Jesus dos Perdões",
  "Bom Princ�pio": "Bom Princípio",
  "Bom Princ�pio do Piau�": "Bom Princípio do Piauí",
  "Bom Sucesso de Itarar�": "Bom Sucesso de Itararé",
  "Bonfim do Piau�": "Bonfim do Piauí",
  "Bonfin�polis": "Bonfinópolis",
  "Bonfin�polis de Minas": "Bonfinópolis de Minas",
  "Bonito de Santa F�": "Bonito de Santa Fé",
  "Bon�polis": "Bonópolis",
  "Boqueir�o": "Boqueirão",
  "Boqueir�o do Le�o": "Boqueirão do Leão",
  "Boqueir�o do Piau�": "Boqueirão do Piauí",
  "Bor�": "Borá",
  "Borac�ia": "Boracéia",
  "Borraz�polis": "Borrazópolis",
  "Botupor�": "Botuporã",
  "Botuver�": "Botuverá",
  "Bra�o do Norte": "Braço do Norte",
  "Bra�o do Trombudo": "Braço do Trombudo",
  "Bragan�a": "Bragança",
  "Bragan�a Paulista": "Bragança Paulista",
  "Br�s Pires": "Brás Pires",
  "Brasil�ndia": "Brasilândia",
  "Brasil�ndia de Minas": "Brasilândia de Minas",
  "Brasil�ndia do Sul": "Brasilândia do Sul",
  "Brasil�ndia do Tocantins": "Brasilândia do Tocantins",
  "Brasil�ia": "Brasiléia",
  "Bras�lia": "Brasília",
  "Bras�lia de Minas": "Brasília de Minas",
  "Bra�na": "Braúna",
  "Bra�nas": "Braúnas",
  "Braz�polis": "Brazópolis",
  "Brej�o": "Brejão",
  "Brejinho de Nazar�": "Brejinho de Nazaré",
  "Brejo do Piau�": "Brejo do Piauí",
  "Brej�es": "Brejões",
  "Brejol�ndia": "Brejolândia",
  "Brit�nia": "Britânia",
  "Brotas de Maca�bas": "Brotas de Macaúbas",
  "Brun�polis": "Brunópolis",
  "Bueno Brand�o": "Bueno Brandão",
  "Buen�polis": "Buenópolis",
  "Bu�que": "Buíque",
  "Buriti de Goi�s": "Buriti de Goiás",
  "Buritin�polis": "Buritinópolis",
  "Buti�": "Butiá",
  "Caapor�": "Caaporã",
  "Caarap�": "Caarapó",
  "Cabaceiras do Paragua�u": "Cabaceiras do Paraguaçu",
  "Cabeceiras do Piau�": "Cabeceiras do Piauí",
  "Cabr�lia Paulista": "Cabrália Paulista",
  "Cabre�va": "Cabreúva",
  "Cabrob�": "Cabrobó",
  "Ca�ador": "Caçador",
  "Ca�apava": "Caçapava",
  "Ca�apava do Sul": "Caçapava do Sul",
  "Cacaul�ndia": "Cacaulândia",
  "C�ceres": "Cáceres",
  "Cachoeira de Goi�s": "Cachoeira de Goiás",
  "Cachoeira de Paje�": "Cachoeira de Pajeú",
  "Cachoeira do Piri�": "Cachoeira do Piriá",
  "Cachoeira dos �ndios": "Cachoeira dos Índios",
  "Ca�u": "Caçu",
  "Cacul�": "Caculé",
  "Ca�m": "Caém",
  "Caetan�polis": "Caetanópolis",
  "Caet�": "Caeté",
  "Caet�s": "Caetés",
  "Caetit�": "Caetité",
  "Cafel�ndia": "Cafelândia",
  "Caiap�nia": "Caiapônia",
  "Caibat�": "Caibaté",
  "Cai�ara": "Caiçara",
  "Cai�ara do Norte": "Caiçara do Norte",
  "Cai�ara do Rio do Vento": "Caiçara do Rio do Vento",
  "Caic�": "Caicó",
  "Caiu�": "Caiuá",
  "Cajapi�": "Cajapió",
  "Cajazeiras do Piau�": "Cajazeiras do Piauí",
  "Cal�ado": "Calçado",
  "Cal�oene": "Calçoene",
  "Caldas Brand�o": "Caldas Brandão",
  "Caldeir�o Grande": "Caldeirão Grande",
  "Caldeir�o Grande do Piau�": "Caldeirão Grande do Piauí",
  "Calif�rnia": "Califórnia",
  "Cama�ari": "Camaçari",
  "Camala�": "Camalaú",
  "Camapu�": "Camapuã",
  "Camaqu�": "Camaquã",
  "Cambar�": "Cambará",
  "Cambar� do Sul": "Cambará do Sul",
  "Camb�": "Cambé",
  "Cambori�": "Camboriú",
  "Cambu�": "Cambuí",
  "Camet�": "Cametá",
  "Camocim de S�o F�lix": "Camocim de São Félix",
  "Campan�rio": "Campanário",
  "Campestre de Goi�s": "Campestre de Goiás",
  "Campestre do Maranh�o": "Campestre do Maranhão",
  "Campina das Miss�es": "Campina das Missões",
  "Campina do Sim�o": "Campina do Simão",
  "Campina�u": "Campinaçu",
  "Campin�polis": "Campinápolis",
  "Campinas do Piau�": "Campinas do Piauí",
  "Campo Alegre de Goi�s": "Campo Alegre de Goiás",
  "Campo Er�": "Campo Erê",
  "Campo Grande do Piau�": "Campo Grande do Piauí",
  "Campo Largo do Piau�": "Campo Largo do Piauí",
  "Campo Limpo de Goi�s": "Campo Limpo de Goiás",
  "Campo Mour�o": "Campo Mourão",
  "Campo Novo de Rond�nia": "Campo Novo de Rondônia",
  "Campos de J�lio": "Campos de Júlio",
  "Campos do Jord�o": "Campos do Jordão",
  "Cana�": "Canaã",
  "Cana� dos Caraj�s": "Canaã dos Carajás",
  "Canan�ia": "Cananéia",
  "Can�polis": "Canápolis",
  "Candel�ria": "Candelária",
  "C�ndido de Abreu": "Cândido de Abreu",
  "C�ndido God�i": "Cândido Godói",
  "C�ndido Mendes": "Cândido Mendes",
  "C�ndido Mota": "Cândido Mota",
  "C�ndido Rodrigues": "Cândido Rodrigues",
  "C�ndido Sales": "Cândido Sales",
  "Cand�i": "Candói",
  "Cangu�u": "Canguçu",
  "Canind�": "Canindé",
  "Canind� de S�o Francisco": "Canindé de São Francisco",
  "Cansan��o": "Cansanção",
  "Cant�": "Cantá",
  "Cap�o Alto": "Capão Alto",
  "Cap�o Bonito": "Capão Bonito",
  "Cap�o Bonito do Sul": "Capão Bonito do Sul",
  "Cap�o da Canoa": "Capão da Canoa",
  "Cap�o do Cip�": "Capão do Cipó",
  "Cap�o do Le�o": "Capão do Leão",
  "Capara�": "Caparaó",
  "Capin�polis": "Capinópolis",
  "Capit�o": "Capitão",
  "Capit�o Andrade": "Capitão Andrade",
  "Capit�o de Campos": "Capitão de Campos",
  "Capit�o En�as": "Capitão Enéas",
  "Capit�o Gerv�sio Oliveira": "Capitão Gervásio Oliveira",
  "Capit�o Le�nidas Marques": "Capitão Leônidas Marques",
  "Capit�o Po�o": "Capitão Poço",
  "Capit�lio": "Capitólio",
  "Cara�": "Caraá",
  "Caracara�": "Caracaraí",
  "Cara�bas": "Caraíbas",
  "Carambe�": "Carambeí",
  "Carana�ba": "Caranaíba",
  "Caranda�": "Carandaí",
  "Carapicu�ba": "Carapicuíba",
  "Cara�bas do Piau�": "Caraúbas do Piauí",
  "Carea�u": "Careaçu",
  "Careiro da V�rzea": "Careiro da Várzea",
  "Caridade do Piau�": "Caridade do Piauí",
  "Carir�": "Cariré",
  "Cariria�u": "Caririaçu",
  "Cari�s": "Cariús",
  "Carl�polis": "Carlópolis",
  "Carm�sia": "Carmésia",
  "Carmo do Parana�ba": "Carmo do Paranaíba",
  "Carmol�ndia": "Carmolândia",
  "Carm�polis": "Carmópolis",
  "Carm�polis de Minas": "Carmópolis de Minas",
  "Carna�ba": "Carnaíba",
  "Carna�ba dos Dantas": "Carnaúba dos Dantas",
  "Carvalh�polis": "Carvalhópolis",
  "C�ssia": "Cássia",
  "C�ssia dos Coqueiros": "Cássia dos Coqueiros",
  "Cassil�ndia": "Cassilândia",
  "Castel�ndia": "Castelândia",
  "Castelo do Piau�": "Castelo do Piauí",
  "Catal�o": "Catalão",
  "Catigu�": "Catiguá",
  "Catol�ndia": "Catolândia",
  "Catol� do Rocha": "Catolé do Rocha",
  "Catu�pe": "Catuípe",
  "Catura�": "Caturaí",
  "Caturit�": "Caturité",
  "Caxing�": "Caxingó",
  "Cear�-Mirim": "Ceará-Mirim",
  "Cedro de S�o Jo�o": "Cedro de São João",
  "Cedro do Abaet�": "Cedro do Abaeté",
  "Centen�rio": "Centenário",
  "Centen�rio do Sul": "Centenário do Sul",
  "Central do Maranh�o": "Central do Maranhão",
  "Centro Novo do Maranh�o": "Centro Novo do Maranhão",
  "Cerqueira C�sar": "Cerqueira César",
  "Cerro Cor�": "Cerro Corá",
  "Ces�rio Lange": "Cesário Lange",
  "C�u Azul": "Céu Azul",
  "Ch� de Alegria": "Chã de Alegria",
  "Ch� Grande": "Chã Grande",
  "Ch� Preta": "Chã Preta",
  "Ch�cara": "Chácara",
  "Chal�": "Chalé",
  "Chapada dos Guimar�es": "Chapada dos Guimarães",
  "Chapada Ga�cha": "Chapada Gaúcha",
  "Chapad�o do C�u": "Chapadão do Céu",
  "Chapad�o do Lageado": "Chapadão do Lageado",
  "Chapad�o do Sul": "Chapadão do Sul",
  "Chapec�": "Chapecó",
  "Chor�": "Choró",
  "Chorroch�": "Chorrochó",
  "Chu�": "Chuí",
  "C�cero Dantas": "Cícero Dantas",
  "Cidade Ga�cha": "Cidade Gaúcha",
  "Cidel�ndia": "Cidelândia",
  "Cip�": "Cipó",
  "Cipot�nea": "Cipotânea",
  "Cir�aco": "Ciríaco",
  "Claro dos Po��es": "Claro dos Poções",
  "Cl�udia": "Cláudia",
  "Cl�udio": "Cláudio",
  "Clevel�ndia": "Clevelândia",
  "Cocalzinho de Goi�s": "Cocalzinho de Goiás",
  "Codaj�s": "Codajás",
  "Cod�": "Codó",
  "Coit� do N�ia": "Coité do Nóia",
  "Col�der": "Colíder",
  "Colm�ia": "Colméia",
  "Col�mbia": "Colômbia",
  "Col�nia do Gurgu�ia": "Colônia do Gurguéia",
  "Col�nia do Piau�": "Colônia do Piauí",
  "Col�nia Leopoldina": "Colônia Leopoldina",
  "Concei��o": "Conceição",
  "Concei��o da Aparecida": "Conceição da Aparecida",
  "Concei��o da Barra": "Conceição da Barra",
  "Concei��o da Barra de Minas": "Conceição da Barra de Minas",
  "Concei��o da Feira": "Conceição da Feira",
  "Concei��o das Alagoas": "Conceição das Alagoas",
  "Concei��o das Pedras": "Conceição das Pedras",
  "Concei��o de Ipanema": "Conceição de Ipanema",
  "Concei��o de Macabu": "Conceição de Macabu",
  "Concei��o do Almeida": "Conceição do Almeida",
  "Concei��o do Araguaia": "Conceição do Araguaia",
  "Concei��o do Canind�": "Conceição do Canindé",
  "Concei��o do Castelo": "Conceição do Castelo",
  "Concei��o do Coit�": "Conceição do Coité",
  "Concei��o do Jacu�pe": "Conceição do Jacuípe",
  "Concei��o do Lago-A�u": "Conceição do Lago-Açu",
  "Concei��o do Mato Dentro": "Conceição do Mato Dentro",
  "Concei��o do Par�": "Conceição do Pará",
  "Concei��o do Rio Verde": "Conceição do Rio Verde",
  "Concei��o do Tocantins": "Conceição do Tocantins",
  "Concei��o dos Ouros": "Conceição dos Ouros",
  "Conc�rdia": "Concórdia",
  "Conc�rdia do Par�": "Concórdia do Pará",
  "Conde�ba": "Condeúba",
  "C�nego Marinho": "Cônego Marinho",
  "Consola��o": "Consolação",
  "Contendas do Sincor�": "Contendas do Sincorá",
  "Cora��o de Jesus": "Coração de Jesus",
  "Cora��o de Maria": "Coração de Maria",
  "Corb�lia": "Corbélia",
  "Cordeir�polis": "Cordeirópolis",
  "Cordisl�ndia": "Cordislândia",
  "Corea�": "Coreaú",
  "Corn�lio Proc�pio": "Cornélio Procópio",
  "Coroat�": "Coroatá",
  "Coronel Jo�o Pessoa": "Coronel João Pessoa",
  "Coronel Jo�o S�": "Coronel João Sá",
  "Coronel Jos� Dias": "Coronel José Dias",
  "C�rrego Danta": "Córrego Danta",
  "C�rrego do Bom Jesus": "Córrego do Bom Jesus",
  "C�rrego do Ouro": "Córrego do Ouro",
  "C�rrego Fundo": "Córrego Fundo",
  "C�rrego Novo": "Córrego Novo",
  "Cort�s": "Cortês",
  "Corumb�": "Corumbá",
  "Corumb� de Goi�s": "Corumbá de Goiás",
  "Corumba�ba": "Corumbaíba",
  "Corumbata�": "Corumbataí",
  "Corumbata� do Sul": "Corumbataí do Sul",
  "Corup�": "Corupá",
  "Cosm�polis": "Cosmópolis",
  "Cotipor�": "Cotiporã",
  "Cotrigua�u": "Cotriguaçu",
  "Couto de Magalh�es de Minas": "Couto de Magalhães de Minas",
  "Couto Magalh�es": "Couto Magalhães",
  "Cra�bas": "Craíbas",
  "Crate�s": "Crateús",
  "Cravol�ndia": "Cravolândia",
  "Crici�ma": "Criciúma",
  "Cris�lita": "Crisólita",
  "Cris�polis": "Crisópolis",
  "Cristal�ndia": "Cristalândia",
  "Cristal�ndia do Piau�": "Cristalândia do Piauí",
  "Crist�lia": "Cristália",
  "Cristian�polis": "Cristianópolis",
  "Cristin�polis": "Cristinápolis",
  "Crist�polis": "Cristópolis",
  "Crix�s": "Crixás",
  "Crix�s do Tocantins": "Crixás do Tocantins",
  "Croat�": "Croatá",
  "Crom�nia": "Cromínia",
  "Crucil�ndia": "Crucilândia",
  "Cruz do Esp�rito Santo": "Cruz do Espírito Santo",
  "Cruz�lia": "Cruzália",
  "Cruzeiro do Igua�u": "Cruzeiro do Iguaçu",
  "Cubat�o": "Cubatão",
  "Cuiab�": "Cuiabá",
  "Cuit�": "Cuité",
  "Cuit� de Mamanguape": "Cuité de Mamanguape",
  "Cunha Por�": "Cunha Porã",
  "Cunhata�": "Cunhataí",
  "Cura��": "Curaçá",
  "Curimat�": "Curimatá",
  "Curion�polis": "Curionópolis",
  "Curi�va": "Curiúva",
  "Curral Novo do Piau�": "Curral Novo do Piauí",
  "Curu�": "Curuá",
  "Curu��": "Curuçá",
  "Curvel�ndia": "Curvelândia",
  "Cust�dia": "Custódia",
  "Damian�polis": "Damianópolis",
  "Dami�o": "Damião",
  "Damol�ndia": "Damolândia",
  "Darcin�polis": "Darcinópolis",
  "D�rio Meira": "Dário Meira",
  "Davin�polis": "Davinópolis",
  "Delfin�polis": "Delfinópolis",
  "Demerval Lob�o": "Demerval Lobão",
  "Deod�polis": "Deodápolis",
  "Dian�polis": "Dianópolis",
  "Dias D'�vila": "Dias D'Ávila",
  "Dion�sio": "Dionísio",
  "Dion�sio Cerqueira": "Dionísio Cerqueira",
  "Divin�sia": "Divinésia",
  "Divino de S�o Louren�o": "Divino de São Lourenço",
  "Divinol�ndia": "Divinolândia",
  "Divinol�ndia de Minas": "Divinolândia de Minas",
  "Divin�polis": "Divinópolis",
  "Divin�polis de Goi�s": "Divinópolis de Goiás",
  "Divin�polis do Tocantins": "Divinópolis do Tocantins",
  "Divis�polis": "Divisópolis",
  "Dois C�rregos": "Dois Córregos",
  "Dois Irm�os": "Dois Irmãos",
  "Dois Irm�os das Miss�es": "Dois Irmãos das Missões",
  "Dois Irm�os do Buriti": "Dois Irmãos do Buriti",
  "Dois Irm�os do Tocantins": "Dois Irmãos do Tocantins",
  "Dolcin�polis": "Dolcinópolis",
  "Dom Bas�lio": "Dom Basílio",
  "Dom Inoc�ncio": "Dom Inocêncio",
  "Dom Pedro de Alc�ntara": "Dom Pedro de Alcântara",
  "Dom Silv�rio": "Dom Silvério",
  "Dom Vi�oso": "Dom Viçoso",
  "Domingos Mour�o": "Domingos Mourão",
  "Dona Eus�bia": "Dona Eusébia",
  "Dona In�s": "Dona Inês",
  "Dores de Guanh�es": "Dores de Guanhães",
  "Dores do Indai�": "Dores do Indaiá",
  "Dores�polis": "Doresópolis",
  "Doutor Maur�cio Cardoso": "Doutor Maurício Cardoso",
  "Doverl�ndia": "Doverlândia",
  "Duer�": "Dueré",
  "Durand�": "Durandé",
  "Echapor�": "Echaporã",
  "Ed�ia": "Edéia",
  "Eirunep�": "Eirunepé",
  "Eldorado do Caraj�s": "Eldorado do Carajás",
  "Elesb�o Veloso": "Elesbão Veloso",
  "Elisi�rio": "Elisiário",
  "El�sio Medrado": "Elísio Medrado",
  "El�i Mendes": "Elói Mendes",
  "Emba�ba": "Embaúba",
  "Embu-Gua�u": "Embu-Guaçu",
  "Emilian�polis": "Emilianópolis",
  "En�as Marques": "Enéas Marques",
  "Engenheiro Beltr�o": "Engenheiro Beltrão",
  "Entre-Iju�s": "Entre-Ijuís",
  "Epitaciol�ndia": "Epitaciolândia",
  "Erer�": "Ererê",
  "�rico Cardoso": "Érico Cardoso",
  "Erv�lia": "Ervália",
  "Esperan�a": "Esperança",
  "Esperan�a do Sul": "Esperança do Sul",
  "Esperan�a Nova": "Esperança Nova",
  "Esperantin�polis": "Esperantinópolis",
  "Espig�o Alto do Igua�u": "Espigão Alto do Iguaçu",
  "Espig�o D'Oeste": "Espigão D'Oeste",
  "Esp�rito Santo": "Espírito Santo",
  "Esp�rito Santo do Dourado": "Espírito Santo do Dourado",
  "Esp�rito Santo do Pinhal": "Espírito Santo do Pinhal",
  "Esp�rito Santo do Turvo": "Espírito Santo do Turvo",
  "Esta��o": "Estação",
  "Est�ncia": "Estância",
  "Est�ncia Velha": "Estância Velha",
  "Estrela do Indai�": "Estrela do Indaiá",
  "Eug�nio de Castro": "Eugênio de Castro",
  "Eugen�polis": "Eugenópolis",
  "Eun�polis": "Eunápolis",
  "Eus�bio": "Eusébio",
  "Ewbank da C�mara": "Ewbank da Câmara",
  "Fartura do Piau�": "Fartura do Piauí",
  "F�tima": "Fátima",
  "F�tima do Sul": "Fátima do Sul",
  "Feij�": "Feijó",
  "Feira Nova do Maranh�o": "Feira Nova do Maranhão",
  "Fel�cio dos Santos": "Felício dos Santos",
  "Felixl�ndia": "Felixlândia",
  "F�nix": "Fênix",
  "Fernando Falc�o": "Fernando Falcão",
  "Fernand�polis": "Fernandópolis",
  "Fern�o": "Fernão",
  "Figueir�o": "Figueirão",
  "Figueir�polis": "Figueirópolis",
  "Figueir�polis D'Oeste": "Figueirópolis D'Oeste",
  "Filad�lfia": "Filadélfia",
  "Firmin�polis": "Firminópolis",
  "Flor do Sert�o": "Flor do Sertão",
  "Flora�": "Floraí",
  "Flores de Goi�s": "Flores de Goiás",
  "Flores do Piau�": "Flores do Piauí",
  "Floresta do Piau�": "Floresta do Piauí",
  "Florest�polis": "Florestópolis",
  "Florian�polis": "Florianópolis",
  "Fl�rida": "Flórida",
  "Fl�rida Paulista": "Flórida Paulista",
  "Flor�nia": "Florínia",
  "Fortaleza do Taboc�o": "Fortaleza do Tabocão",
  "Foz do Igua�u": "Foz do Iguaçu",
  "Foz do Jord�o": "Foz do Jordão",
  "Francin�polis": "Francinópolis",
  "Francisco Badar�": "Francisco Badaró",
  "Francisco Beltr�o": "Francisco Beltrão",
  "Francisco S�": "Francisco Sá",
  "Francisc�polis": "Franciscópolis",
  "Frei Inoc�ncio": "Frei Inocêncio",
  "Frei Rog�rio": "Frei Rogério",
  "Fund�o": "Fundão",
  "Funil�ndia": "Funilândia",
  "G�lia": "Gália",
  "Galil�ia": "Galiléia",
  "Galv�o": "Galvão",
  "Gameleira de Goi�s": "Gameleira de Goiás",
  "Gar�a": "Garça",
  "Garraf�o do Norte": "Garrafão do Norte",
  "Gast�o Vidigal": "Gastão Vidigal",
  "Ga�cha do Norte": "Gaúcha do Norte",
  "Gavi�o": "Gavião",
  "Gavi�o Peixoto": "Gavião Peixoto",
  "General C�mara": "General Câmara",
  "Get�lio Vargas": "Getúlio Vargas",
  "Gilbu�s": "Gilbués",
  "Giru�": "Giruá",
  "Glaucil�ndia": "Glaucilândia",
  "Glic�rio": "Glicério",
  "Gl�ria": "Glória",
  "Gl�ria D'Oeste": "Glória D'Oeste",
  "Gl�ria de Dourados": "Glória de Dourados",
  "Gl�ria do Goit�": "Glória do Goitá",
  "Goian�": "Goianá",
  "Goian�polis": "Goianápolis",
  "Goian�sia": "Goianésia",
  "Goian�sia do Par�": "Goianésia do Pará",
  "Goi�nia": "Goiânia",
  "Goi�s": "Goiás",
  "Goioer�": "Goioerê",
  "Gon�alves": "Gonçalves",
  "Gon�alves Dias": "Gonçalves Dias",
  "Gouvel�ndia": "Gouvelândia",
  "Governador Edison Lob�o": "Governador Edison Lobão",
  "Governador Eug�nio Barros": "Governador Eugênio Barros",
  "Gra�a": "Graça",
  "Gra�a Aranha": "Graça Aranha",
  "Graja�": "Grajaú",
  "Gr�o Mogol": "Grão Mogol",
  "Gr�o Par�": "Grão Pará",
  "Gravat�": "Gravatá",
  "Gravata�": "Gravataí",
  "Groa�ras": "Groaíras",
  "Gua�u�": "Guaçuí",
  "Gua�ba": "Guaíba",
  "Guai�ara": "Guaiçara",
  "Guaimb�": "Guaimbê",
  "Gua�ra": "Guaíra",
  "Guaira��": "Guairaçá",
  "Guai�ba": "Guaiúba",
  "Guajar�": "Guajará",
  "Guajar�-Mirim": "Guajará-Mirim",
  "Guamar�": "Guamaré",
  "Guanh�es": "Guanhães",
  "Guapia�u": "Guapiaçu",
  "Guap�": "Guapó",
  "Guapor�": "Guaporé",
  "Guar�": "Guará",
  "Guara�a�": "Guaraçaí",
  "Guara�": "Guaraí",
  "Guara�ta": "Guaraíta",
  "Guaran�sia": "Guaranésia",
  "Guarani das Miss�es": "Guarani das Missões",
  "Guarani de Goi�s": "Guarani de Goiás",
  "Guarania�u": "Guaraniaçu",
  "Guarant�": "Guarantã",
  "Guarant� do Norte": "Guarantã do Norte",
  "Guaraque�aba": "Guaraqueçaba",
  "Guarar�": "Guarará",
  "Guaratinguet�": "Guaratinguetá",
  "Guare�": "Guareí",
  "Guaruj�": "Guarujá",
  "Guaruj� do Sul": "Guarujá do Sul",
  "Guatamb�": "Guatambú",
  "Guatapar�": "Guatapará",
  "Guaxup�": "Guaxupé",
  "Guimar�es": "Guimarães",
  "Guimar�nia": "Guimarânia",
  "Gurinhat�": "Gurinhatã",
  "Gurinh�m": "Gurinhém",
  "Gurj�o": "Gurjão",
  "Gurup�": "Gurupá",
  "Guzol�ndia": "Guzolândia",
  "Heitora�": "Heitoraí",
  "Heli�polis": "Heliópolis",
  "Hercul�ndia": "Herculândia",
  "Hidrol�ndia": "Hidrolândia",
  "Hon�rio Serpa": "Honório Serpa",
  "Hortol�ndia": "Hortolândia",
  "Hugo Napole�o": "Hugo Napoleão",
  "Humait�": "Humaitá",
  "Ia�u": "Iaçu",
  "Ibat�": "Ibaté",
  "Ibi�": "Ibiá",
  "Ibia��": "Ibiaçá",
  "Ibia�": "Ibiaí",
  "Ibiassuc�": "Ibiassucê",
  "Ibicara�": "Ibicaraí",
  "Ibicar�": "Ibicaré",
  "Ibicu�": "Ibicuí",
  "Ibipor�": "Ibiporã",
  "Ibir�": "Ibirá",
  "Ibira�u": "Ibiraçu",
  "Ibirapu�": "Ibirapuã",
  "Ibirapuit�": "Ibirapuitã",
  "Ibirit�": "Ibirité",
  "Ibirub�": "Ibirubá",
  "Ibitit�": "Ibititá",
  "Ibiti�ra de Minas": "Ibitiúra de Minas",
  "Ibi�na": "Ibiúna",
  "Icapu�": "Icapuí",
  "I�ara": "Içara",
  "Icara� de Minas": "Icaraí de Minas",
  "Icara�ma": "Icaraíma",
  "Ic�m": "Icém",
  "Ic�": "Icó",
  "Iep�": "Iepê",
  "Igapor�": "Igaporã",
  "Igara�u do Tiet�": "Igaraçu do Tietê",
  "Igarap�": "Igarapé",
  "Igarap� do Meio": "Igarapé do Meio",
  "Igarap� Grande": "Igarapé Grande",
  "Igarap�-A�u": "Igarapé-Açu",
  "Igarap�-Miri": "Igarapé-Miri",
  "Igarat�": "Igaratá",
  "Igrapi�na": "Igrapiúna",
  "Igua�": "Iguaí",
  "Iguara�u": "Iguaraçu",
  "Iju�": "Ijuí",
  "Ilha de Itamarac�": "Ilha de Itamaracá",
  "Ilh�us": "Ilhéus",
  "Ilic�nea": "Ilicínea",
  "Il�polis": "Ilópolis",
  "Imaru�": "Imaruí",
  "Imba�": "Imbaú",
  "Imb�": "Imbé",
  "Imb� de Minas": "Imbé de Minas",
  "In�cio Martins": "Inácio Martins",
  "Inaciol�ndia": "Inaciolândia",
  "Inaj�": "Inajá",
  "Independ�ncia": "Independência",
  "Indian�polis": "Indianópolis",
  "Indiapor�": "Indiaporã",
  "Indiava�": "Indiavaí",
  "Ing�": "Ingá",
  "Inga�": "Ingaí",
  "Inhacor�": "Inhacorá",
  "Inha�ma": "Inhaúma",
  "Inoc�ncia": "Inocência",
  "In�bia Paulista": "Inúbia Paulista",
  "Iomer�": "Iomerê",
  "Ipangua�u": "Ipanguaçu",
  "Ip�": "Ipê",
  "Ipecaet�": "Ipecaetá",
  "Iper�": "Iperó",
  "Ipe�na": "Ipeúna",
  "Ipia�u": "Ipiaçu",
  "Ipia�": "Ipiaú",
  "Ipigu�": "Ipiguá",
  "Ipir�": "Ipirá",
  "Ipiranga de Goi�s": "Ipiranga de Goiás",
  "Ipiranga do Piau�": "Ipiranga do Piauí",
  "Ipixuna do Par�": "Ipixuna do Pará",
  "Ipor�": "Iporá",
  "Ipor� do Oeste": "Iporã do Oeste",
  "Ipu�": "Ipuã",
  "Ipua�u": "Ipuaçu",
  "Ipui�na": "Ipuiúna",
  "Iracem�polis": "Iracemápolis",
  "Ira�": "Iraí",
  "Ira� de Minas": "Iraí de Minas",
  "Irapu�": "Irapuã",
  "Irar�": "Irará",
  "Irau�uba": "Irauçuba",
  "Irec�": "Irecê",
  "Irine�polis": "Irineópolis",
  "Isa�as Coelho": "Isaías Coelho",
  "Israel�ndia": "Israelândia",
  "It�": "Itá",
  "Itaber�": "Itaberá",
  "Itabera�": "Itaberaí",
  "Itabora�": "Itaboraí",
  "Itacaj�": "Itacajá",
  "Itacar�": "Itacaré",
  "Itaet�": "Itaeté",
  "Itagib�": "Itagibá",
  "Itagua�u": "Itaguaçu",
  "Itagua�u da Bahia": "Itaguaçu da Bahia",
  "Itagua�": "Itaguaí",
  "Itaguaj�": "Itaguajé",
  "Ita�": "Itaí",
  "Itai�aba": "Itaiçaba",
  "Itain�polis": "Itainópolis",
  "Itai�polis": "Itaiópolis",
  "Itaipava do Graja�": "Itaipava do Grajaú",
  "Itaip�": "Itaipé",
  "Itaipul�ndia": "Itaipulândia",
  "Itaj�": "Itajá",
  "Itaja�": "Itajaí",
  "Itaju do Col�nia": "Itaju do Colônia",
  "Itajub�": "Itajubá",
  "Itaju�pe": "Itajuípe",
  "Itambarac�": "Itambaracá",
  "Itamb�": "Itambé",
  "Itamb� do Mato Dentro": "Itambé do Mato Dentro",
  "Itanha�m": "Itanhaém",
  "Itanhang�": "Itanhangá",
  "Itanh�m": "Itanhém",
  "Ita�ca": "Itaóca",
  "Itapaj�": "Itapajé",
  "Itap�": "Itapé",
  "Itaperu�u": "Itaperuçu",
  "Itapirapu�": "Itapirapuã",
  "Itapirapu� Paulista": "Itapirapuã Paulista",
  "Itapi�na": "Itapiúna",
  "Itapo�": "Itapoá",
  "It�polis": "Itápolis",
  "Itapor�": "Itaporã",
  "Itapor� do Tocantins": "Itaporã do Tocantins",
  "Itapu� do Oeste": "Itapuã do Oeste",
  "Itapu�": "Itapuí",
  "Itaquira�": "Itaquiraí",
  "Itarar�": "Itararé",
  "Itarum�": "Itarumã",
  "Itatiaiu�u": "Itatiaiuçu",
  "Ita� de Minas": "Itaú de Minas",
  "Ita�ba": "Itaúba",
  "Itau�u": "Itauçu",
  "Ita�na": "Itaúna",
  "Ita�na do Sul": "Itaúna do Sul",
  "Itinga do Maranh�o": "Itinga do Maranhão",
  "Itirapu�": "Itirapuã",
  "Itiru�u": "Itiruçu",
  "Iti�ba": "Itiúba",
  "Itoror�": "Itororó",
  "Itua�u": "Ituaçu",
  "Ituber�": "Ituberá",
  "Iui�": "Iuiú",
  "I�na": "Iúna",
  "Iva�": "Ivaí",
  "Ivaipor�": "Ivaiporã",
  "Ivat�": "Ivaté",
  "Ivol�ndia": "Ivolândia",
  "Ivor�": "Ivorá",
  "Jaboat�o dos Guararapes": "Jaboatão dos Guararapes",
  "Jabor�": "Jaborá",
  "Ja�an�": "Jaçanã",
  "Jacara�": "Jacaraú",
  "Jacar� dos Homens": "Jacaré dos Homens",
  "Jacare�": "Jacareí",
  "Jacobina do Piau�": "Jacobina do Piauí",
  "Jacu�": "Jacuí",
  "Jacu�pe": "Jacuípe",
  "Jacund�": "Jacundá",
  "Jaguapit�": "Jaguapitã",
  "Jaguara�u": "Jaguaraçu",
  "Jaguar�o": "Jaguarão",
  "Jaguar�": "Jaguaré",
  "Jaguaria�va": "Jaguariaíva",
  "Jaguari�na": "Jaguariúna",
  "Ja�ba": "Jaíba",
  "Jaic�s": "Jaicós",
  "Jana�ba": "Janaúba",
  "Janda�ra": "Jandaíra",
  "Jandu�s": "Janduís",
  "Jani�polis": "Janiópolis",
  "Janu�ria": "Januária",
  "Janu�rio Cicco": "Januário Cicco",
  "Japara�ba": "Japaraíba",
  "Japoat�": "Japoatã",
  "Japor�": "Japorã",
  "Japur�": "Japurá",
  "Jaragu�": "Jaraguá",
  "Jaragu� do Sul": "Jaraguá do Sul",
  "Jardim do Serid�": "Jardim do Seridó",
  "Jardin�polis": "Jardinópolis",
  "Jata�": "Jataí",
  "Jata�ba": "Jataúba",
  "Jate�": "Jateí",
  "Jatob�": "Jatobá",
  "Jatob� do Piau�": "Jatobá do Piauí",
  "Ja�": "Jaú",
  "Ja� do Tocantins": "Jaú do Tocantins",
  "Jequi� da Praia": "Jequiá da Praia",
  "Jequi�": "Jequié",
  "Jequita�": "Jequitaí",
  "Jequitib�": "Jequitibá",
  "Jeric�": "Jericó",
  "Jer�nimo Monteiro": "Jerônimo Monteiro",
  "Jesu�nia": "Jesuânia",
  "Jesu�tas": "Jesuítas",
  "Jes�polis": "Jesúpolis",
  "Ji-Paran�": "Ji-Paraná",
  "Jiquiri��": "Jiquiriçá",
  "Jita�na": "Jitaúna",
  "Joa�aba": "Joaçaba",
  "Joa�ma": "Joaíma",
  "Joan�sia": "Joanésia",
  "Joan�polis": "Joanópolis",
  "Jo�o Alfredo": "João Alfredo",
  "Jo�o C�mara": "João Câmara",
  "Jo�o Costa": "João Costa",
  "Jo�o Dias": "João Dias",
  "Jo�o Dourado": "João Dourado",
  "Jo�o Lisboa": "João Lisboa",
  "Jo�o Monlevade": "João Monlevade",
  "Jo�o Neiva": "João Neiva",
  "Jo�o Pessoa": "João Pessoa",
  "Jo�o Pinheiro": "João Pinheiro",
  "Jo�o Ramalho": "João Ramalho",
  "Joaquim Fel�cio": "Joaquim Felício",
  "Joaquim T�vora": "Joaquim Távora",
  "J�ia": "Jóia",
  "Jord�nia": "Jordânia",
  "Jord�o": "Jordão",
  "Jos� Boiteux": "José Boiteux",
  "Jos� Bonif�cio": "José Bonifácio",
  "Jos� da Penha": "José da Penha",
  "Jos� de Freitas": "José de Freitas",
  "Jos� Gon�alves de Minas": "José Gonçalves de Minas",
  "Jos� Raydan": "José Raydan",
  "Josel�ndia": "Joselândia",
  "Josen�polis": "Josenópolis",
  "Jovi�nia": "Joviânia",
  "Juarez T�vora": "Juarez Távora",
  "Juazeiro do Piau�": "Juazeiro do Piauí",
  "Juc�s": "Jucás",
  "Jucuru�u": "Jucuruçu",
  "Ju�na": "Juína",
  "J�lio Borges": "Júlio Borges",
  "J�lio de Castilhos": "Júlio de Castilhos",
  "J�lio Mesquita": "Júlio Mesquita",
  "Junco do Maranh�o": "Junco do Maranhão",
  "Junco do Serid�": "Junco do Seridó",
  "Jundi�": "Jundiá",
  "Jundia�": "Jundiaí",
  "Jundia� do Sul": "Jundiaí do Sul",
  "Junqueir�polis": "Junqueirópolis",
  "Jupi�": "Jupiá",
  "Juqui�": "Juquiá",
  "Juru�": "Juruá",
  "Juta�": "Jutaí",
  "Juven�lia": "Juvenília",
  "Kalor�": "Kaloré",
  "L�brea": "Lábrea",
  "Lacerd�polis": "Lacerdópolis",
  "Lad�rio": "Ladário",
  "Lagoa da Confus�o": "Lagoa da Confusão",
  "Lagoa de S�o Francisco": "Lagoa de São Francisco",
  "Lagoa do Barro do Piau�": "Lagoa do Barro do Piauí",
  "Lagoa do Piau�": "Lagoa do Piauí",
  "Lagoa do S�tio": "Lagoa do Sítio",
  "Lagoa dos Tr�s Cantos": "Lagoa dos Três Cantos",
  "Lagoa Grande do Maranh�o": "Lagoa Grande do Maranhão",
  "Lago�o": "Lagoão",
  "Lagoinha do Piau�": "Lagoinha do Piauí",
  "Laguna Carap�": "Laguna Carapã",
  "Laje do Muria�": "Laje do Muriaé",
  "Lajed�o": "Lajedão",
  "Lamar�o": "Lamarão",
  "Lap�o": "Lapão",
  "Lav�nia": "Lavínia",
  "Lebon R�gis": "Lebon Régis",
  "Len��is": "Lençóis",
  "Len��is Paulista": "Lençóis Paulista",
  "Leopoldo de Bulh�es": "Leopoldo de Bulhões",
  "Le�polis": "Leópolis",
  "Lic�nio de Almeida": "Licínio de Almeida",
  "Lidian�polis": "Lidianópolis",
  "Lind�ia": "Lindóia",
  "Lind�ia do Sul": "Lindóia do Sul",
  "Luc�lia": "Lucélia",
  "Lucian�polis": "Lucianópolis",
  "Lucr�cia": "Lucrécia",
  "Lu�s Ant�nio": "Luís Antônio",
  "Lu�s Correia": "Luís Correia",
  "Lu�s Domingues": "Luís Domingues",
  "Lu�s Eduardo Magalh�es": "Luís Eduardo Magalhães",
  "Lu�s Gomes": "Luís Gomes",
  "Luisl�ndia": "Luislândia",
  "Luizi�nia": "Luiziânia",
  "Lumin�rias": "Luminárias",
  "Lup�rcio": "Lupércio",
  "Lupion�polis": "Lupionópolis",
  "Lut�cia": "Lutécia",
  "Luzi�nia": "Luziânia",
  "Luzil�ndia": "Luzilândia",
  "Luzin�polis": "Luzinópolis",
  "Maca�": "Macaé",
  "Maca�ba": "Macaíba",
  "Ma�ambar�": "Maçambará",
  "Macap�": "Macapá",
  "Maca�bas": "Macaúbas",
  "Maced�nia": "Macedônia",
  "Macei�": "Maceió",
  "Macurur�": "Macururé",
  "M�e D'�gua": "Mãe D'Água",
  "M�e do Rio": "Mãe do Rio",
  "Magalh�es Barata": "Magalhães Barata",
  "Magalh�es de Almeida": "Magalhães de Almeida",
  "Mag�": "Magé",
  "Mairipor�": "Mairiporã",
  "Mamba�": "Mambaí",
  "Mambor�": "Mamborê",
  "Mana�ra": "Manaíra",
  "M�ncio Lima": "Mâncio Lima",
  "Mandagua�u": "Mandaguaçu",
  "Manfrin�polis": "Manfrinópolis",
  "Manhua�u": "Manhuaçu",
  "Manicor�": "Manicoré",
  "Manoel Em�dio": "Manoel Emídio",
  "Mansid�o": "Mansidão",
  "Manten�polis": "Mantenópolis",
  "Maquin�": "Maquiné",
  "Marab�": "Marabá",
  "Marab� Paulista": "Marabá Paulista",
  "Maraca�um�": "Maracaçumé",
  "Maraca�": "Maracaí",
  "Maracaj�": "Maracajá",
  "Maracan�": "Maracanã",
  "Maracana�": "Maracanaú",
  "Marac�s": "Maracás",
  "Maraj� do Sena": "Marajá do Sena",
  "Maranh�ozinho": "Maranhãozinho",
  "Marat�": "Maratá",
  "Marata�zes": "Marataízes",
  "Mara�": "Maraú",
  "Marca��o": "Marcação",
  "Marcel�ndia": "Marcelândia",
  "Marcion�lio Souza": "Marcionílio Souza",
  "Marcol�ndia": "Marcolândia",
  "Marechal C�ndido Rondon": "Marechal Cândido Rondon",
  "Maria da F�": "Maria da Fé",
  "Marian�polis do Tocantins": "Marianópolis do Tocantins",
  "Maric�": "Maricá",
  "Maril�ndia": "Marilândia",
  "Maril�ndia do Sul": "Marilândia do Sul",
  "Mar�lia": "Marília",
  "Maring�": "Maringá",
  "Marin�polis": "Marinópolis",
  "M�rio Campos": "Mário Campos",
  "Mari�polis": "Mariópolis",
  "Marip�": "Maripá",
  "Marip� de Minas": "Maripá de Minas",
  "Mariz�polis": "Marizópolis",
  "Marli�ria": "Marliéria",
  "Marmel�polis": "Marmelópolis",
  "Martin�pole": "Martinópole",
  "Martin�polis": "Martinópolis",
  "Marzag�o": "Marzagão",
  "Massap�": "Massapê",
  "Massap� do Piau�": "Massapê do Piauí",
  "Mata de S�o Jo�o": "Mata de São João",
  "Mat�o": "Matão",
  "Matel�ndia": "Matelândia",
  "Materl�ndia": "Materlândia",
  "Matias Ol�mpio": "Matias Olímpio",
  "Matip�": "Matipó",
  "Mato Leit�o": "Mato Leitão",
  "Mat�es": "Matões",
  "Mat�es do Norte": "Matões do Norte",
  "Matrinch�": "Matrinchã",
  "Matup�": "Matupá",
  "Matur�ia": "Maturéia",
  "Mau�": "Mauá",
  "Mau� da Serra": "Mauá da Serra",
  "Mau�s": "Maués",
  "Mauril�ndia": "Maurilândia",
  "Mauril�ndia do Tocantins": "Maurilândia do Tocantins",
  "Mazag�o": "Mazagão",
  "Medicil�ndia": "Medicilândia",
  "Melga�o": "Melgaço",
  "Mendon�a": "Mendonça",
  "Merc�s": "Mercês",
  "Mes�polis": "Mesópolis",
  "Miguel Le�o": "Miguel Leão",
  "Miguel�polis": "Miguelópolis",
  "Milagres do Maranh�o": "Milagres do Maranhão",
  "Milh�": "Milhã",
  "Milton Brand�o": "Milton Brandão",
  "Mimoso de Goi�s": "Mimoso de Goiás",
  "Mina�u": "Minaçu",
  "Minador do Negr�o": "Minador do Negrão",
  "Minas do Le�o": "Minas do Leão",
  "Mineiros do Tiet�": "Mineiros do Tietê",
  "Miragua�": "Miraguaí",
  "Mira�": "Miraí",
  "Mira�ma": "Miraíma",
  "Mirand�polis": "Mirandópolis",
  "Mirassol�ndia": "Mirassolândia",
  "Mirav�nia": "Miravânia",
  "Miss�o Velha": "Missão Velha",
  "Mogi Gua�u": "Mogi Guaçu",
  "Moipor�": "Moiporá",
  "Moju� dos Campos": "Mojuí dos Campos",
  "Momba�a": "Mombaça",
  "Mon��o": "Monção",
  "Mon��es": "Monções",
  "Monda�": "Mondaí",
  "Mongagu�": "Mongaguá",
  "Monsenhor Hip�lito": "Monsenhor Hipólito",
  "Montalv�nia": "Montalvânia",
  "Monte Alegre de Goi�s": "Monte Alegre de Goiás",
  "Monte Alegre do Piau�": "Monte Alegre do Piauí",
  "Monte Apraz�vel": "Monte Aprazível",
  "Monte Si�o": "Monte Sião",
  "Monteir�polis": "Monteirópolis",
  "Montes Claros de Goi�s": "Montes Claros de Goiás",
  "Mora�jo": "Moraújo",
  "Moreil�ndia": "Moreilândia",
  "Morma�o": "Mormaço",
  "Morpar�": "Morpará",
  "Morro Agudo de Goi�s": "Morro Agudo de Goiás",
  "Morro Cabe�a No Tempo": "Morro Cabeça No Tempo",
  "Morro da Fuma�a": "Morro da Fumaça",
  "Morro da Gar�a": "Morro da Garça",
  "Morro do Chap�u": "Morro do Chapéu",
  "Morro do Chap�u do Piau�": "Morro do Chapéu do Piauí",
  "Moss�medes": "Mossâmedes",
  "Mossor�": "Mossoró",
  "Mozarl�ndia": "Mozarlândia",
  "Muan�": "Muaná",
  "Mucaja�": "Mucajaí",
  "Mucug�": "Mucugê",
  "Mu�um": "Muçum",
  "Muitos Cap�es": "Muitos Capões",
  "Muqu�m de S�o Francisco": "Muquém de São Francisco",
  "Muria�": "Muriaé",
  "Muricil�ndia": "Muricilândia",
  "Mutu�pe": "Mutuípe",
  "Mutun�polis": "Mutunópolis",
  "N�o-Me-Toque": "Não-Me-Toque",
  "Natal�ndia": "Natalândia",
  "Nat�rcia": "Natércia",
  "Navira�": "Naviraí",
  "Nazar�": "Nazaré",
  "Nazar� da Mata": "Nazaré da Mata",
  "Nazar� do Piau�": "Nazaré do Piauí",
  "Nazar� Paulista": "Nazaré Paulista",
  "Naz�ria": "Nazária",
  "Naz�rio": "Nazário",
  "Ne�polis": "Neópolis",
  "Ner�polis": "Nerópolis",
  "Nhamund�": "Nhamundá",
  "Nilo Pe�anha": "Nilo Peçanha",
  "Nil�polis": "Nilópolis",
  "Nipo�": "Nipoã",
  "Niquel�ndia": "Niquelândia",
  "N�sia Floresta": "Nísia Floresta",
  "Niter�i": "Niterói",
  "Nortel�ndia": "Nortelândia",
  "Nossa Senhora da Gl�ria": "Nossa Senhora da Glória",
  "Nossa Senhora das Gra�as": "Nossa Senhora das Graças",
  "Nossa Senhora de Nazar�": "Nossa Senhora de Nazaré",
  "Nossa Senhora dos Rem�dios": "Nossa Senhora dos Remédios",
  "Nova Alian�a": "Nova Aliança",
  "Nova Alian�a do Iva�": "Nova Aliança do Ivaí",
  "Nova Am�rica": "Nova América",
  "Nova Am�rica da Colina": "Nova América da Colina",
  "Nova Ara��": "Nova Araçá",
  "Nova Bel�m": "Nova Belém",
  "Nova Brasil�ndia": "Nova Brasilândia",
  "Nova Brasil�ndia D'Oeste": "Nova Brasilândia D'Oeste",
  "Nova Br�scia": "Nova Bréscia",
  "Nova Cana�": "Nova Canaã",
  "Nova Cana� do Norte": "Nova Canaã do Norte",
  "Nova Cana� Paulista": "Nova Canaã Paulista",
  "Nova Candel�ria": "Nova Candelária",
  "Nova Crix�s": "Nova Crixás",
  "Nova Esperan�a": "Nova Esperança",
  "Nova Esperan�a do Piri�": "Nova Esperança do Piriá",
  "Nova Esperan�a do Sudoeste": "Nova Esperança do Sudoeste",
  "Nova Esperan�a do Sul": "Nova Esperança do Sul",
  "Nova F�tima": "Nova Fátima",
  "Nova Gl�ria": "Nova Glória",
  "Nova Ibi�": "Nova Ibiá",
  "Nova Igua�u": "Nova Iguaçu",
  "Nova Igua�u de Goi�s": "Nova Iguaçu de Goiás",
  "Nova Independ�ncia": "Nova Independência",
  "Nova Luzit�nia": "Nova Luzitânia",
  "Nova Mamor�": "Nova Mamoré",
  "Nova Maril�ndia": "Nova Marilândia",
  "Nova Maring�": "Nova Maringá",
  "Nova M�dica": "Nova Módica",
  "Nova Nazar�": "Nova Nazaré",
  "Nova Ol�mpia": "Nova Olímpia",
  "Nova Olinda do Maranh�o": "Nova Olinda do Maranhão",
  "Nova P�dua": "Nova Pádua",
  "Nova Petr�polis": "Nova Petrópolis",
  "Nova Prata do Igua�u": "Nova Prata do Iguaçu",
  "Nova Reden��o": "Nova Redenção",
  "Nova Rosal�ndia": "Nova Rosalândia",
  "Nova Santa B�rbara": "Nova Santa Bárbara",
  "Nova Ubirat�": "Nova Ubiratã",
  "Nova Uni�o": "Nova União",
  "Nova Ven�cia": "Nova Venécia",
  "Nova Vi�osa": "Nova Viçosa",
  "Novo Air�o": "Novo Airão",
  "Novo Aripuan�": "Novo Aripuanã",
  "Novo Oriente do Piau�": "Novo Oriente do Piauí",
  "Novo Santo Ant�nio": "Novo Santo Antônio",
  "Novo S�o Joaquim": "Novo São Joaquim",
  "�bidos": "Óbidos",
  "Ocau�u": "Ocauçu",
  "Oeiras do Par�": "Oeiras do Pará",
  "�leo": "Óleo",
  "Olho D'�gua": "Olho D'Água",
  "Olho D'�gua das Cunh�s": "Olho D'Água das Cunhãs",
  "Olho D'�gua das Flores": "Olho D'Água das Flores",
  "Olho D'�gua do Casado": "Olho D'Água do Casado",
  "Olho D'�gua do Piau�": "Olho D'Água do Piauí",
  "Olho D'�gua Grande": "Olho D'Água Grande",
  "Olho-d'�gua do Borges": "Olho-d'Água do Borges",
  "Olhos-d'�gua": "Olhos-d'Água",
  "Ol�mpia": "Olímpia",
  "Ol�mpio Noronha": "Olímpio Noronha",
  "Olinda Nova do Maranh�o": "Olinda Nova do Maranhão",
  "Oliveira de F�tima": "Oliveira de Fátima",
  "Oliven�a": "Olivença",
  "On�a de Pitangui": "Onça de Pitangui",
  "Orat�rios": "Oratórios",
  "Orindi�va": "Orindiúva",
  "Oriximin�": "Oriximiná",
  "Oriz�nia": "Orizânia",
  "Orl�ndia": "Orlândia",
  "Orob�": "Orobó",
  "Oroc�": "Orocó",
  "Or�s": "Orós",
  "Os�rio": "Osório",
  "Otac�lio Costa": "Otacílio Costa",
  "Our�m": "Ourém",
  "Ouri�angas": "Ouriçangas",
  "Ouril�ndia do Norte": "Ourilândia do Norte",
  "Ouro Verde de Goi�s": "Ouro Verde de Goiás",
  "Ourol�ndia": "Ourolândia",
  "Pacaj�": "Pacajá",
  "Pa�o do Lumiar": "Paço do Lumiar",
  "Pacuj�": "Pacujá",
  "Padre Para�so": "Padre Paraíso",
  "Pai�andu": "Paiçandu",
  "Paje� do Piau�": "Pajeú do Piauí",
  "Palestina de Goi�s": "Palestina de Goiás",
  "Palestina do Par�": "Palestina do Pará",
  "Palho�a": "Palhoça",
  "Palm�cia": "Palmácia",
  "Palmeira das Miss�es": "Palmeira das Missões",
  "Palmeira do Piau�": "Palmeira do Piauí",
  "Palmeira dos �ndios": "Palmeira dos Índios",
  "Palmeir�ndia": "Palmeirândia",
  "Palmeiras de Goi�s": "Palmeiras de Goiás",
  "Palmeir�polis": "Palmeirópolis",
  "Palmin�polis": "Palminópolis",
  "Palm�polis": "Palmópolis",
  "Panam�": "Panamá",
  "P�o de A��car": "Pão de Açúcar",
  "Paquet�": "Paquetá",
  "Par� de Minas": "Pará de Minas",
  "Paragua�u": "Paraguaçu",
  "Paragua�u Paulista": "Paraguaçu Paulista",
  "Para�": "Paraí",
  "Para�ba do Sul": "Paraíba do Sul",
  "Para�so": "Paraíso",
  "Para�so das �guas": "Paraíso das Águas",
  "Para�so do Norte": "Paraíso do Norte",
  "Para�so do Sul": "Paraíso do Sul",
  "Para�so do Tocantins": "Paraíso do Tocantins",
  "Parais�polis": "Paraisópolis",
  "Paran�": "Paraná",
  "Paranagu�": "Paranaguá",
  "Parana�ba": "Paranaíba",
  "Parana�ta": "Paranaíta",
  "Paranapu�": "Paranapuã",
  "Paranava�": "Paranavaí",
  "Parapu�": "Parapuã",
  "Para�na": "Paraúna",
  "Pariquera-A�u": "Pariquera-Açu",
  "Parnagu�": "Parnaguá",
  "Parna�ba": "Parnaíba",
  "Parob�": "Parobé",
  "Passab�m": "Passabém",
  "Passagem Franca do Piau�": "Passagem Franca do Piauí",
  "Patos do Piau�": "Patos do Piauí",
  "Patroc�nio": "Patrocínio",
  "Patroc�nio do Muria�": "Patrocínio do Muriaé",
  "Patroc�nio Paulista": "Patrocínio Paulista",
  "Pau D'Arco do Piau�": "Pau D'Arco do Piauí",
  "Paula C�ndido": "Paula Cândido",
  "Paulic�ia": "Paulicéia",
  "Paul�nia": "Paulínia",
  "Paulist�nia": "Paulistânia",
  "Pav�o": "Pavão",
  "P� de Serra": "Pé de Serra",
  "Pe�anha": "Peçanha",
  "Pedra do Indai�": "Pedra do Indaiá",
  "Pedran�polis": "Pedranópolis",
  "Pedr�o": "Pedrão",
  "Pedrin�polis": "Pedrinópolis",
  "Pedro Can�rio": "Pedro Canário",
  "Pedro do Ros�rio": "Pedro do Rosário",
  "Pedro Os�rio": "Pedro Osório",
  "Pedro R�gis": "Pedro Régis",
  "Peju�ara": "Pejuçara",
  "Pen�polis": "Penápolis",
  "Pend�ncias": "Pendências",
  "Perdig�o": "Perdigão",
  "Perd�es": "Perdões",
  "Peritor�": "Peritoró",
  "P�rola": "Pérola",
  "P�rola D'Oeste": "Pérola D'Oeste",
  "Perol�ndia": "Perolândia",
  "Peru�be": "Peruíbe",
  "Petrol�ndia": "Petrolândia",
  "Petrolina de Goi�s": "Petrolina de Goiás",
  "Petr�polis": "Petrópolis",
  "Pia�abu�u": "Piaçabuçu",
  "Pianc�": "Piancó",
  "Piat�": "Piatã",
  "Picada Caf�": "Picada Café",
  "Pi�arra": "Piçarra",
  "Picu�": "Picuí",
  "Pi�n": "Piên",
  "Pil�o Arcado": "Pilão Arcado",
  "Pilar de Goi�s": "Pilar de Goiás",
  "Pil�es": "Pilões",
  "Pil�ezinhos": "Pilõezinhos",
  "Pinda�": "Pindaí",
  "Pindar�-Mirim": "Pindaré-Mirim",
  "Pindoba�u": "Pindobaçu",
  "Pingo-D'�gua": "Pingo-D'Água",
  "Pinhal de S�o Bento": "Pinhal de São Bento",
  "Pinhal�o": "Pinhalão",
  "Pinh�o": "Pinhão",
  "Pint�polis": "Pintópolis",
  "Pira�": "Piraí",
  "Pira� do Norte": "Piraí do Norte",
  "Pira� do Sul": "Piraí do Sul",
  "Piraju�": "Pirajuí",
  "Pirangu�u": "Piranguçu",
  "Pirap�": "Pirapó",
  "Piraqu�": "Piraquê",
  "Pira�ba": "Piraúba",
  "Piren�polis": "Pirenópolis",
  "Pirip�": "Piripá",
  "Pi�ma": "Piúma",
  "Pl�cido de Castro": "Plácido de Castro",
  "Planaltina do Paran�": "Planaltina do Paraná",
  "Po�": "Poá",
  "Po��o": "Poção",
  "Po��o de Pedras": "Poção de Pedras",
  "Po�o Branco": "Poço Branco",
  "Po�o Dantas": "Poço Dantas",
  "Po�o das Antas": "Poço das Antas",
  "Po�o das Trincheiras": "Poço das Trincheiras",
  "Po�o de Jos� de Moura": "Poço de José de Moura",
  "Po�o Fundo": "Poço Fundo",
  "Po�o Redondo": "Poço Redondo",
  "Po�o Verde": "Poço Verde",
  "Po��es": "Poções",
  "Pocon�": "Poconé",
  "Po�os de Caldas": "Poços de Caldas",
  "Pomp�ia": "Pompéia",
  "Pomp�u": "Pompéu",
  "Ponga�": "Pongaí",
  "Ponta Por�": "Ponta Porã",
  "Pontal do Paran�": "Pontal do Paraná",
  "Pont�o": "Pontão",
  "Porci�ncula": "Porciúncula",
  "Port�o": "Portão",
  "Porteir�o": "Porteirão",
  "Portel�ndia": "Portelândia",
  "Porto Alegre do Piau�": "Porto Alegre do Piauí",
  "Porto dos Ga�chos": "Porto dos Gaúchos",
  "Porto Esperidi�o": "Porto Esperidião",
  "Porto Mau�": "Porto Mauá",
  "Porto Real do Col�gio": "Porto Real do Colégio",
  "Porto Rico do Maranh�o": "Porto Rico do Maranhão",
  "Porto Uni�o": "Porto União",
  "Porto Vit�ria": "Porto Vitória",
  "Pot�": "Poté",
  "Potiragu�": "Potiraguá",
  "Poxor�u": "Poxoréu",
  "Pracu�ba": "Pracuúba",
  "Prad�polis": "Pradópolis",
  "Prata do Piau�": "Prata do Piauí",
  "Prat�nia": "Pratânia",
  "Prat�polis": "Pratápolis",
  "Presidente Epit�cio": "Presidente Epitácio",
  "Presidente Get�lio": "Presidente Getúlio",
  "Presidente J�nio Quadros": "Presidente Jânio Quadros",
  "Presidente M�dici": "Presidente Médici",
  "Presidente Oleg�rio": "Presidente Olegário",
  "Primavera de Rond�nia": "Primavera de Rondônia",
  "Promiss�o": "Promissão",
  "Propri�": "Propriá",
  "Prot�sio Alves": "Protásio Alves",
  "Prudent�polis": "Prudentópolis",
  "Puxinan�": "Puxinanã",
  "Quara�": "Quaraí",
  "Quarto Centen�rio": "Quarto Centenário",
  "Quat�": "Quatá",
  "Quatigu�": "Quatiguá",
  "Quatro Irm�os": "Quatro Irmãos",
  "Quedas do Igua�u": "Quedas do Iguaçu",
  "Quer�ncia": "Querência",
  "Quer�ncia do Norte": "Querência do Norte",
  "Quipap�": "Quipapá",
  "Quirin�polis": "Quirinópolis",
  "Quissam�": "Quissamã",
  "Quiterian�polis": "Quiterianópolis",
  "Quixad�": "Quixadá",
  "Quixel�": "Quixelô",
  "Quixer�": "Quixeré",
  "Ramil�ndia": "Ramilândia",
  "Rebou�as": "Rebouças",
  "Recursol�ndia": "Recursolândia",
  "Reden��o": "Redenção",
  "Reden��o da Serra": "Redenção da Serra",
  "Reden��o do Gurgu�ia": "Redenção do Gurguéia",
  "Regenera��o": "Regeneração",
  "Regente Feij�": "Regente Feijó",
  "Regin�polis": "Reginópolis",
  "Rem�gio": "Remígio",
  "Renascen�a": "Renascença",
  "Reserva do Caba�al": "Reserva do Cabaçal",
  "Reserva do Igua�u": "Reserva do Iguaçu",
  "Restinga S�ca": "Restinga Sêca",
  "Retirol�ndia": "Retirolândia",
  "Riach�o": "Riachão",
  "Riach�o das Neves": "Riachão das Neves",
  "Riach�o do Bacamarte": "Riachão do Bacamarte",
  "Riach�o do Dantas": "Riachão do Dantas",
  "Riach�o do Jacu�pe": "Riachão do Jacuípe",
  "Riach�o do Po�o": "Riachão do Poço",
  "Riacho de Santo Ant�nio": "Riacho de Santo Antônio",
  "Rian�polis": "Rianápolis",
  "Ribeira do Piau�": "Ribeira do Piauí",
  "Ribeir�o": "Ribeirão",
  "Ribeir�o Bonito": "Ribeirão Bonito",
  "Ribeir�o Branco": "Ribeirão Branco",
  "Ribeir�o Cascalheira": "Ribeirão Cascalheira",
  "Ribeir�o Claro": "Ribeirão Claro",
  "Ribeir�o Corrente": "Ribeirão Corrente",
  "Ribeir�o das Neves": "Ribeirão das Neves",
  "Ribeir�o do Largo": "Ribeirão do Largo",
  "Ribeir�o do Pinhal": "Ribeirão do Pinhal",
  "Ribeir�o do Sul": "Ribeirão do Sul",
  "Ribeir�o dos �ndios": "Ribeirão dos Índios",
  "Ribeir�o Grande": "Ribeirão Grande",
  "Ribeir�o Pires": "Ribeirão Pires",
  "Ribeir�o Preto": "Ribeirão Preto",
  "Ribeir�o Vermelho": "Ribeirão Vermelho",
  "Ribeir�ozinho": "Ribeirãozinho",
  "Ribeiro Gon�alves": "Ribeiro Gonçalves",
  "Ribeir�polis": "Ribeirópolis",
  "Rinc�o": "Rincão",
  "Rin�polis": "Rinópolis",
  "Rio Bonito do Igua�u": "Rio Bonito do Iguaçu",
  "Rio Branco do Iva�": "Rio Branco do Ivaí",
  "Rio da Concei��o": "Rio da Conceição",
  "Rio do Ant�nio": "Rio do Antônio",
  "Rio dos �ndios": "Rio dos Índios",
  "Rio Grande do Piau�": "Rio Grande do Piauí",
  "Rio Parana�ba": "Rio Paranaíba",
  "Riol�ndia": "Riolândia",
  "Rit�polis": "Ritápolis",
  "Rol�ndia": "Rolândia",
  "Romel�ndia": "Romelândia",
  "Rondol�ndia": "Rondolândia",
  "Rondon do Par�": "Rondon do Pará",
  "Rondon�polis": "Rondonópolis",
  "Rorain�polis": "Rorainópolis",
  "Ros�rio": "Rosário",
  "Ros�rio da Limeira": "Rosário da Limeira",
  "Ros�rio do Catete": "Rosário do Catete",
  "Ros�rio do Iva�": "Rosário do Ivaí",
  "Ros�rio do Sul": "Rosário do Sul",
  "Ros�rio Oeste": "Rosário Oeste",
  "Rubi�cea": "Rubiácea",
  "Rubin�ia": "Rubinéia",
  "Rur�polis": "Rurópolis",
  "Sabar�": "Sabará",
  "Sab�udia": "Sabáudia",
  "Sabin�polis": "Sabinópolis",
  "Sagrada Fam�lia": "Sagrada Família",
  "Sair�": "Sairé",
  "Sales�polis": "Salesópolis",
  "Salgado de S�o F�lix": "Salgado de São Félix",
  "Salin�polis": "Salinópolis",
  "Salmour�o": "Salmourão",
  "Salo�": "Saloá",
  "Salto do C�u": "Salto do Céu",
  "Salto do Itarar�": "Salto do Itararé",
  "Salto do Jacu�": "Salto do Jacuí",
  "Salvador das Miss�es": "Salvador das Missões",
  "Samba�ba": "Sambaíba",
  "Sanclerl�ndia": "Sanclerlândia",
  "Sandol�ndia": "Sandolândia",
  "Sang�o": "Sangão",
  "Sanhar�": "Sanharó",
  "Santa Ad�lia": "Santa Adélia",
  "Santa Am�lia": "Santa Amélia",
  "Santa B�rbara": "Santa Bárbara",
  "Santa B�rbara D'Oeste": "Santa Bárbara D'Oeste",
  "Santa B�rbara de Goi�s": "Santa Bárbara de Goiás",
  "Santa B�rbara do Leste": "Santa Bárbara do Leste",
  "Santa B�rbara do Monte Verde": "Santa Bárbara do Monte Verde",
  "Santa B�rbara do Par�": "Santa Bárbara do Pará",
  "Santa B�rbara do Sul": "Santa Bárbara do Sul",
  "Santa B�rbara do Tug�rio": "Santa Bárbara do Tugúrio",
  "Santa Br�gida": "Santa Brígida",
  "Santa Cec�lia": "Santa Cecília",
  "Santa Cec�lia do Pav�o": "Santa Cecília do Pavão",
  "Santa Cec�lia do Sul": "Santa Cecília do Sul",
  "Santa Cruz Cabr�lia": "Santa Cruz Cabrália",
  "Santa Cruz da Concei��o": "Santa Cruz da Conceição",
  "Santa Cruz da Esperan�a": "Santa Cruz da Esperança",
  "Santa Cruz da Vit�ria": "Santa Cruz da Vitória",
  "Santa Cruz de Goi�s": "Santa Cruz de Goiás",
  "Santa Cruz do Piau�": "Santa Cruz do Piauí",
  "Santa Efig�nia de Minas": "Santa Efigênia de Minas",
  "Santa F�": "Santa Fé",
  "Santa F� de Goi�s": "Santa Fé de Goiás",
  "Santa F� de Minas": "Santa Fé de Minas",
  "Santa F� do Araguaia": "Santa Fé do Araguaia",
  "Santa F� do Sul": "Santa Fé do Sul",
  "Santa Filomena do Maranh�o": "Santa Filomena do Maranhão",
  "Santa Helena de Goi�s": "Santa Helena de Goiás",
  "Santa In�s": "Santa Inês",
  "Santa Isabel do Iva�": "Santa Isabel do Ivaí",
  "Santa Izabel do Par�": "Santa Izabel do Pará",
  "Santa L�cia": "Santa Lúcia",
  "Santa Luzia do Par�": "Santa Luzia do Pará",
  "Santa Luzia do Paru�": "Santa Luzia do Paruá",
  "Santa Maria da Vit�ria": "Santa Maria da Vitória",
  "Santa Maria de Jetib�": "Santa Maria de Jetibá",
  "Santa Maria do Cambuc�": "Santa Maria do Cambucá",
  "Santa Maria do Par�": "Santa Maria do Pará",
  "Santa Maria do Sua�u�": "Santa Maria do Suaçuí",
  "Santa M�nica": "Santa Mônica",
  "Santa Quit�ria": "Santa Quitéria",
  "Santa Quit�ria do Maranh�o": "Santa Quitéria do Maranhão",
  "Santa Rita de C�ssia": "Santa Rita de Cássia",
  "Santa Rita do Sapuca�": "Santa Rita do Sapucaí",
  "Santa Rosa de Goi�s": "Santa Rosa de Goiás",
  "Santa Rosa do Piau�": "Santa Rosa do Piauí",
  "Santa Tereza de Goi�s": "Santa Tereza de Goiás",
  "Santa Terezinha de Goi�s": "Santa Terezinha de Goiás",
  "Santa Vit�ria": "Santa Vitória",
  "Santa Vit�ria do Palmar": "Santa Vitória do Palmar",
  "Santana de Parna�ba": "Santana de Parnaíba",
  "Santana do Acara�": "Santana do Acaraú",
  "Santana do Garamb�u": "Santana do Garambéu",
  "Santana do Itarar�": "Santana do Itararé",
  "Santana do Jacar�": "Santana do Jacaré",
  "Santana do Manhua�u": "Santana do Manhuaçu",
  "Santana do Maranh�o": "Santana do Maranhão",
  "Santana do Munda�": "Santana do Mundaú",
  "Santana do Para�so": "Santana do Paraíso",
  "Santana do Piau�": "Santana do Piauí",
  "Santana do S�o Francisco": "Santana do São Francisco",
  "Santana do Serid�": "Santana do Seridó",
  "Santan�polis": "Santanópolis",
  "Santar�m": "Santarém",
  "Santar�m Novo": "Santarém Novo",
  "Santo Amaro do Maranh�o": "Santo Amaro do Maranhão",
  "Santo Anast�cio": "Santo Anastácio",
  "Santo Andr�": "Santo André",
  "Santo �ngelo": "Santo Ângelo",
  "Santo Ant�nio": "Santo Antônio",
  "Santo Ant�nio da Alegria": "Santo Antônio da Alegria",
  "Santo Ant�nio da Barra": "Santo Antônio da Barra",
  "Santo Ant�nio da Patrulha": "Santo Antônio da Patrulha",
  "Santo Ant�nio da Platina": "Santo Antônio da Platina",
  "Santo Ant�nio das Miss�es": "Santo Antônio das Missões",
  "Santo Ant�nio de Goi�s": "Santo Antônio de Goiás",
  "Santo Ant�nio de Jesus": "Santo Antônio de Jesus",
  "Santo Ant�nio de Lisboa": "Santo Antônio de Lisboa",
  "Santo Ant�nio de P�dua": "Santo Antônio de Pádua",
  "Santo Ant�nio de Posse": "Santo Antônio de Posse",
  "Santo Ant�nio do Amparo": "Santo Antônio do Amparo",
  "Santo Ant�nio do Aracangu�": "Santo Antônio do Aracanguá",
  "Santo Ant�nio do Aventureiro": "Santo Antônio do Aventureiro",
  "Santo Ant�nio do Caiu�": "Santo Antônio do Caiuá",
  "Santo Ant�nio do Descoberto": "Santo Antônio do Descoberto",
  "Santo Ant�nio do Grama": "Santo Antônio do Grama",
  "Santo Ant�nio do I��": "Santo Antônio do Içá",
  "Santo Ant�nio do Itamb�": "Santo Antônio do Itambé",
  "Santo Ant�nio do Jacinto": "Santo Antônio do Jacinto",
  "Santo Ant�nio do Jardim": "Santo Antônio do Jardim",
  "Santo Ant�nio do Leste": "Santo Antônio do Leste",
  "Santo Ant�nio do Leverger": "Santo Antônio do Leverger",
  "Santo Ant�nio do Monte": "Santo Antônio do Monte",
  "Santo Ant�nio do Palma": "Santo Antônio do Palma",
  "Santo Ant�nio do Para�so": "Santo Antônio do Paraíso",
  "Santo Ant�nio do Pinhal": "Santo Antônio do Pinhal",
  "Santo Ant�nio do Planalto": "Santo Antônio do Planalto",
  "Santo Ant�nio do Retiro": "Santo Antônio do Retiro",
  "Santo Ant�nio do Rio Abaixo": "Santo Antônio do Rio Abaixo",
  "Santo Ant�nio do Sudoeste": "Santo Antônio do Sudoeste",
  "Santo Ant�nio do Tau�": "Santo Antônio do Tauá",
  "Santo Ant�nio dos Lopes": "Santo Antônio dos Lopes",
  "Santo Ant�nio dos Milagres": "Santo Antônio dos Milagres",
  "Santo Est�v�o": "Santo Estêvão",
  "Santo Hip�lito": "Santo Hipólito",
  "Santo In�cio": "Santo Inácio",
  "Santo In�cio do Piau�": "Santo Inácio do Piauí",
  "Sant�polis do Aguape�": "Santópolis do Aguapeí",
  "S�o Benedito": "São Benedito",
  "S�o Benedito do Rio Preto": "São Benedito do Rio Preto",
  "S�o Benedito do Sul": "São Benedito do Sul",
  "S�o Bentinho": "São Bentinho",
  "S�o Bento": "São Bento",
  "S�o Bento Abade": "São Bento Abade",
  "S�o Bento do Norte": "São Bento do Norte",
  "S�o Bento do Sapuca�": "São Bento do Sapucaí",
  "S�o Bento do Sul": "São Bento do Sul",
  "S�o Bento do Tocantins": "São Bento do Tocantins",
  "S�o Bento do Trair�": "São Bento do Trairí",
  "S�o Bento do Una": "São Bento do Una",
  "S�o Bernardino": "São Bernardino",
  "S�o Bernardo": "São Bernardo",
  "S�o Bernardo do Campo": "São Bernardo do Campo",
  "S�o Bonif�cio": "São Bonifácio",
  "S�o Borja": "São Borja",
  "S�o Br�s": "São Brás",
  "S�o Br�s do Sua�u�": "São Brás do Suaçuí",
  "S�o Braz do Piau�": "São Braz do Piauí",
  "S�o Caetano de Odivelas": "São Caetano de Odivelas",
  "S�o Caetano do Sul": "São Caetano do Sul",
  "S�o Caitano": "São Caitano",
  "S�o Carlos": "São Carlos",
  "S�o Carlos do Iva�": "São Carlos do Ivaí",
  "S�o Crist�v�o": "São Cristóvão",
  "S�o Cristov�o do Sul": "São Cristovão do Sul",
  "S�o Desid�rio": "São Desidério",
  "S�o Domingos": "São Domingos",
  "S�o Domingos das Dores": "São Domingos das Dores",
  "S�o Domingos do Araguaia": "São Domingos do Araguaia",
  "S�o Domingos do Azeit�o": "São Domingos do Azeitão",
  "S�o Domingos do Capim": "São Domingos do Capim",
  "S�o Domingos do Cariri": "São Domingos do Cariri",
  "S�o Domingos do Maranh�o": "São Domingos do Maranhão",
  "S�o Domingos do Norte": "São Domingos do Norte",
  "S�o Domingos do Prata": "São Domingos do Prata",
  "S�o Domingos do Sul": "São Domingos do Sul",
  "S�o Felipe": "São Felipe",
  "S�o Felipe D'Oeste": "São Felipe D'Oeste",
  "S�o F�lix": "São Félix",
  "S�o F�lix de Balsas": "São Félix de Balsas",
  "S�o F�lix de Minas": "São Félix de Minas",
  "S�o F�lix do Araguaia": "São Félix do Araguaia",
  "S�o F�lix do Coribe": "São Félix do Coribe",
  "S�o F�lix do Piau�": "São Félix do Piauí",
  "S�o F�lix do Tocantins": "São Félix do Tocantins",
  "S�o F�lix do Xingu": "São Félix do Xingu",
  "S�o Fernando": "São Fernando",
  "S�o Fid�lis": "São Fidélis",
  "S�o Francisco": "São Francisco",
  "S�o Francisco de Assis": "São Francisco de Assis",
  "S�o Francisco de Assis do Piau�": "São Francisco de Assis do Piauí",
  "S�o Francisco de Goi�s": "São Francisco de Goiás",
  "S�o Francisco de Itabapoana": "São Francisco de Itabapoana",
  "S�o Francisco de Paula": "São Francisco de Paula",
  "S�o Francisco de Sales": "São Francisco de Sales",
  "S�o Francisco do Brej�o": "São Francisco do Brejão",
  "S�o Francisco do Conde": "São Francisco do Conde",
  "S�o Francisco do Gl�ria": "São Francisco do Glória",
  "S�o Francisco do Guapor�": "São Francisco do Guaporé",
  "S�o Francisco do Maranh�o": "São Francisco do Maranhão",
  "S�o Francisco do Oeste": "São Francisco do Oeste",
  "S�o Francisco do Par�": "São Francisco do Pará",
  "S�o Francisco do Piau�": "São Francisco do Piauí",
  "S�o Francisco do Sul": "São Francisco do Sul",
  "S�o Gabriel": "São Gabriel",
  "S�o Gabriel da Cachoeira": "São Gabriel da Cachoeira",
  "S�o Gabriel da Palha": "São Gabriel da Palha",
  "S�o Gabriel do Oeste": "São Gabriel do Oeste",
  "S�o Geraldo": "São Geraldo",
  "S�o Geraldo da Piedade": "São Geraldo da Piedade",
  "S�o Geraldo do Araguaia": "São Geraldo do Araguaia",
  "S�o Geraldo do Baixio": "São Geraldo do Baixio",
  "S�o Gon�alo": "São Gonçalo",
  "S�o Gon�alo do Abaet�": "São Gonçalo do Abaeté",
  "S�o Gon�alo do Amarante": "São Gonçalo do Amarante",
  "S�o Gon�alo do Gurgu�ia": "São Gonçalo do Gurguéia",
  "S�o Gon�alo do Par�": "São Gonçalo do Pará",
  "S�o Gon�alo do Piau�": "São Gonçalo do Piauí",
  "S�o Gon�alo do Rio Abaixo": "São Gonçalo do Rio Abaixo",
  "S�o Gon�alo do Rio Preto": "São Gonçalo do Rio Preto",
  "S�o Gon�alo do Sapuca�": "São Gonçalo do Sapucaí",
  "S�o Gon�alo dos Campos": "São Gonçalo dos Campos",
  "S�o Gotardo": "São Gotardo",
  "S�o Jer�nimo": "São Jerônimo",
  "S�o Jer�nimo da Serra": "São Jerônimo da Serra",
  "S�o Jo�o": "São João",
  "S�o Jo�o Batista": "São João Batista",
  "S�o Jo�o Batista do Gl�ria": "São João Batista do Glória",
  "S�o Jo�o D'Alian�a": "São João D'Aliança",
  "S�o Jo�o da Baliza": "São João da Baliza",
  "S�o Jo�o da Barra": "São João da Barra",
  "S�o Jo�o da Boa Vista": "São João da Boa Vista",
  "S�o Jo�o da Canabrava": "São João da Canabrava",
  "S�o Jo�o da Fronteira": "São João da Fronteira",
  "S�o Jo�o da Lagoa": "São João da Lagoa",
  "S�o Jo�o da Mata": "São João da Mata",
  "S�o Jo�o da Para�na": "São João da Paraúna",
  "S�o Jo�o da Ponta": "São João da Ponta",
  "S�o Jo�o da Ponte": "São João da Ponte",
  "S�o Jo�o da Serra": "São João da Serra",
  "S�o Jo�o da Urtiga": "São João da Urtiga",
  "S�o Jo�o da Varjota": "São João da Varjota",
  "S�o Jo�o das Duas Pontes": "São João das Duas Pontes",
  "S�o Jo�o das Miss�es": "São João das Missões",
  "S�o Jo�o de Iracema": "São João de Iracema",
  "S�o Jo�o de Meriti": "São João de Meriti",
  "S�o Jo�o de Pirabas": "São João de Pirabas",
  "S�o Jo�o Del Rei": "São João Del Rei",
  "S�o Jo�o do Araguaia": "São João do Araguaia",
  "S�o Jo�o do Arraial": "São João do Arraial",
  "S�o Jo�o do Caiu�": "São João do Caiuá",
  "S�o Jo�o do Cariri": "São João do Cariri",
  "S�o Jo�o do Car�": "São João do Carú",
  "S�o Jo�o do Itaperi�": "São João do Itaperiú",
  "S�o Jo�o do Iva�": "São João do Ivaí",
  "S�o Jo�o do Jaguaribe": "São João do Jaguaribe",
  "S�o Jo�o do Manhua�u": "São João do Manhuaçu",
  "S�o Jo�o do Manteninha": "São João do Manteninha",
  "S�o Jo�o do Oeste": "São João do Oeste",
  "S�o Jo�o do Oriente": "São João do Oriente",
  "S�o Jo�o do Pacu�": "São João do Pacuí",
  "S�o Jo�o do Para�so": "São João do Paraíso",
  "S�o Jo�o do Pau D'Alho": "São João do Pau D'Alho",
  "S�o Jo�o do Piau�": "São João do Piauí",
  "S�o Jo�o do Pol�sine": "São João do Polêsine",
  "S�o Jo�o do Rio do Peixe": "São João do Rio do Peixe",
  "S�o Jo�o do Sabugi": "São João do Sabugi",
  "S�o Jo�o do Soter": "São João do Soter",
  "S�o Jo�o do Sul": "São João do Sul",
  "S�o Jo�o do Tigre": "São João do Tigre",
  "S�o Jo�o do Triunfo": "São João do Triunfo",
  "S�o Jo�o dos Patos": "São João dos Patos",
  "S�o Jo�o Evangelista": "São João Evangelista",
  "S�o Jo�o Nepomuceno": "São João Nepomuceno",
  "S�o Joaquim": "São Joaquim",
  "S�o Joaquim da Barra": "São Joaquim da Barra",
  "S�o Joaquim de Bicas": "São Joaquim de Bicas",
  "S�o Joaquim do Monte": "São Joaquim do Monte",
  "S�o Jorge": "São Jorge",
  "S�o Jorge D'Oeste": "São Jorge D'Oeste",
  "S�o Jorge do Iva�": "São Jorge do Ivaí",
  "S�o Jorge do Patroc�nio": "São Jorge do Patrocínio",
  "S�o Jos�": "São José",
  "S�o Jos� da Barra": "São José da Barra",
  "S�o Jos� da Bela Vista": "São José da Bela Vista",
  "S�o Jos� da Boa Vista": "São José da Boa Vista",
  "S�o Jos� da Coroa Grande": "São José da Coroa Grande",
  "S�o Jos� da Lagoa Tapada": "São José da Lagoa Tapada",
  "S�o Jos� da Laje": "São José da Laje",
  "S�o Jos� da Lapa": "São José da Lapa",
  "S�o Jos� da Safira": "São José da Safira",
  "S�o Jos� da Tapera": "São José da Tapera",
  "S�o Jos� da Varginha": "São José da Varginha",
  "S�o Jos� da Vit�ria": "São José da Vitória",
  "S�o Jos� das Miss�es": "São José das Missões",
  "S�o Jos� das Palmeiras": "São José das Palmeiras",
  "S�o Jos� de Caiana": "São José de Caiana",
  "S�o Jos� de Espinharas": "São José de Espinharas",
  "S�o Jos� de Mipibu": "São José de Mipibu",
  "S�o Jos� de Piranhas": "São José de Piranhas",
  "S�o Jos� de Princesa": "São José de Princesa",
  "S�o Jos� de Ribamar": "São José de Ribamar",
  "S�o Jos� de Ub�": "São José de Ubá",
  "S�o Jos� do Alegre": "São José do Alegre",
  "S�o Jos� do Barreiro": "São José do Barreiro",
  "S�o Jos� do Belmonte": "São José do Belmonte",
  "S�o Jos� do Bonfim": "São José do Bonfim",
  "S�o Jos� do Brejo do Cruz": "São José do Brejo do Cruz",
  "S�o Jos� do Cal�ado": "São José do Calçado",
  "S�o Jos� do Campestre": "São José do Campestre",
  "S�o Jos� do Cedro": "São José do Cedro",
  "S�o Jos� do Cerrito": "São José do Cerrito",
  "S�o Jos� do Divino": "São José do Divino",
  "S�o Jos� do Egito": "São José do Egito",
  "S�o Jos� do Goiabal": "São José do Goiabal",
  "S�o Jos� do Herval": "São José do Herval",
  "S�o Jos� do Hort�ncio": "São José do Hortêncio",
  "S�o Jos� do Inhacor�": "São José do Inhacorá",
  "S�o Jos� do Jacu�pe": "São José do Jacuípe",
  "S�o Jos� do Jacuri": "São José do Jacuri",
  "S�o Jos� do Mantimento": "São José do Mantimento",
  "S�o Jos� do Norte": "São José do Norte",
  "S�o Jos� do Ouro": "São José do Ouro",
  "S�o Jos� do Peixe": "São José do Peixe",
  "S�o Jos� do Piau�": "São José do Piauí",
  "S�o Jos� do Povo": "São José do Povo",
  "S�o Jos� do Rio Claro": "São José do Rio Claro",
  "S�o Jos� do Rio Pardo": "São José do Rio Pardo",
  "S�o Jos� do Rio Preto": "São José do Rio Preto",
  "S�o Jos� do Sabugi": "São José do Sabugi",
  "S�o Jos� do Serid�": "São José do Seridó",
  "S�o Jos� do Sul": "São José do Sul",
  "S�o Jos� do Vale do Rio Preto": "São José do Vale do Rio Preto",
  "S�o Jos� do Xingu": "São José do Xingu",
  "S�o Jos� dos Ausentes": "São José dos Ausentes",
  "S�o Jos� dos Bas�lios": "São José dos Basílios",
  "S�o Jos� dos Campos": "São José dos Campos",
  "S�o Jos� dos Cordeiros": "São José dos Cordeiros",
  "S�o Jos� dos Pinhais": "São José dos Pinhais",
  "S�o Jos� dos Quatro Marcos": "São José dos Quatro Marcos",
  "S�o Jos� dos Ramos": "São José dos Ramos",
  "S�o Juli�o": "São Julião",
  "S�o Leopoldo": "São Leopoldo",
  "S�o Louren�o": "São Lourenço",
  "S�o Louren�o da Mata": "São Lourenço da Mata",
  "S�o Louren�o da Serra": "São Lourenço da Serra",
  "S�o Louren�o do Oeste": "São Lourenço do Oeste",
  "S�o Louren�o do Piau�": "São Lourenço do Piauí",
  "S�o Louren�o do Sul": "São Lourenço do Sul",
  "S�o Ludgero": "São Ludgero",
  "S�o Lu�s": "São Luís",
  "S�o Lu�s de Montes Belos": "São Luís de Montes Belos",
  "S�o Lu�s do Curu": "São Luís do Curu",
  "S�o Lu�s do Paraitinga": "São Luís do Paraitinga",
  "S�o Luis do Piau�": "São Luis do Piauí",
  "S�o Lu�s do Quitunde": "São Luís do Quitunde",
  "S�o Lu�s Gonzaga do Maranh�o": "São Luís Gonzaga do Maranhão",
  "S�o Luiz": "São Luiz",
  "S�o Lu�z do Norte": "São Luíz do Norte",
  "S�o Luiz Gonzaga": "São Luiz Gonzaga",
  "S�o Mamede": "São Mamede",
  "S�o Manoel do Paran�": "São Manoel do Paraná",
  "S�o Manuel": "São Manuel",
  "S�o Marcos": "São Marcos",
  "S�o Martinho": "São Martinho",
  "S�o Martinho da Serra": "São Martinho da Serra",
  "S�o Mateus": "São Mateus",
  "S�o Mateus do Maranh�o": "São Mateus do Maranhão",
  "S�o Mateus do Sul": "São Mateus do Sul",
  "S�o Miguel": "São Miguel",
  "S�o Miguel Arcanjo": "São Miguel Arcanjo",
  "S�o Miguel da Baixa Grande": "São Miguel da Baixa Grande",
  "S�o Miguel da Boa Vista": "São Miguel da Boa Vista",
  "S�o Miguel das Matas": "São Miguel das Matas",
  "S�o Miguel das Miss�es": "São Miguel das Missões",
  "S�o Miguel de Taipu": "São Miguel de Taipu",
  "S�o Miguel do Aleixo": "São Miguel do Aleixo",
  "S�o Miguel do Anta": "São Miguel do Anta",
  "S�o Miguel do Araguaia": "São Miguel do Araguaia",
  "S�o Miguel do Fidalgo": "São Miguel do Fidalgo",
  "S�o Miguel do Gostoso": "São Miguel do Gostoso",
  "S�o Miguel do Guam�": "São Miguel do Guamá",
  "S�o Miguel do Guapor�": "São Miguel do Guaporé",
  "S�o Miguel do Igua�u": "São Miguel do Iguaçu",
  "S�o Miguel do Oeste": "São Miguel do Oeste",
  "S�o Miguel do Passa Quatro": "São Miguel do Passa Quatro",
  "S�o Miguel do Tapuio": "São Miguel do Tapuio",
  "S�o Miguel do Tocantins": "São Miguel do Tocantins",
  "S�o Miguel dos Campos": "São Miguel dos Campos",
  "S�o Miguel dos Milagres": "São Miguel dos Milagres",
  "S�o Nicolau": "São Nicolau",
  "S�o Patr�cio": "São Patrício",
  "S�o Paulo": "São Paulo",
  "S�o Paulo das Miss�es": "São Paulo das Missões",
  "S�o Paulo de Oliven�a": "São Paulo de Olivença",
  "S�o Paulo do Potengi": "São Paulo do Potengi",
  "S�o Pedro": "São Pedro",
  "S�o Pedro da �gua Branca": "São Pedro da Água Branca",
  "S�o Pedro da Aldeia": "São Pedro da Aldeia",
  "S�o Pedro da Cipa": "São Pedro da Cipa",
  "S�o Pedro da Serra": "São Pedro da Serra",
  "S�o Pedro da Uni�o": "São Pedro da União",
  "S�o Pedro das Miss�es": "São Pedro das Missões",
  "S�o Pedro de Alc�ntara": "São Pedro de Alcântara",
  "S�o Pedro do Buti�": "São Pedro do Butiá",
  "S�o Pedro do Igua�u": "São Pedro do Iguaçu",
  "S�o Pedro do Iva�": "São Pedro do Ivaí",
  "S�o Pedro do Paran�": "São Pedro do Paraná",
  "S�o Pedro do Piau�": "São Pedro do Piauí",
  "S�o Pedro do Sua�u�": "São Pedro do Suaçuí",
  "S�o Pedro do Sul": "São Pedro do Sul",
  "S�o Pedro do Turvo": "São Pedro do Turvo",
  "S�o Pedro dos Crentes": "São Pedro dos Crentes",
  "S�o Pedro dos Ferros": "São Pedro dos Ferros",
  "S�o Rafael": "São Rafael",
  "S�o Raimundo das Mangabeiras": "São Raimundo das Mangabeiras",
  "S�o Raimundo do Doca Bezerra": "São Raimundo do Doca Bezerra",
  "S�o Raimundo Nonato": "São Raimundo Nonato",
  "S�o Roberto": "São Roberto",
  "S�o Rom�o": "São Romão",
  "S�o Roque": "São Roque",
  "S�o Roque de Minas": "São Roque de Minas",
  "S�o Roque do Cana�": "São Roque do Canaã",
  "S�o Salvador do Tocantins": "São Salvador do Tocantins",
  "S�o Sebasti�o": "São Sebastião",
  "S�o Sebasti�o da Amoreira": "São Sebastião da Amoreira",
  "S�o Sebasti�o da Bela Vista": "São Sebastião da Bela Vista",
  "S�o Sebasti�o da Boa Vista": "São Sebastião da Boa Vista",
  "S�o Sebasti�o da Grama": "São Sebastião da Grama",
  "S�o Sebasti�o da Vargem Alegre": "São Sebastião da Vargem Alegre",
  "S�o Sebasti�o de Lagoa de Ro�a": "São Sebastião de Lagoa de Roça",
  "S�o Sebasti�o do Alto": "São Sebastião do Alto",
  "S�o Sebasti�o do Anta": "São Sebastião do Anta",
  "S�o Sebasti�o do Ca�": "São Sebastião do Caí",
  "S�o Sebasti�o do Maranh�o": "São Sebastião do Maranhão",
  "S�o Sebasti�o do Oeste": "São Sebastião do Oeste",
  "S�o Sebasti�o do Para�so": "São Sebastião do Paraíso",
  "S�o Sebasti�o do Pass�": "São Sebastião do Passé",
  "S�o Sebasti�o do Rio Preto": "São Sebastião do Rio Preto",
  "S�o Sebasti�o do Rio Verde": "São Sebastião do Rio Verde",
  "S�o Sebasti�o do Tocantins": "São Sebastião do Tocantins",
  "S�o Sebasti�o do Uatum�": "São Sebastião do Uatumã",
  "S�o Sebasti�o do Umbuzeiro": "São Sebastião do Umbuzeiro",
  "S�o Sep�": "São Sepé",
  "S�o Sim�o": "São Simão",
  "S�o Thom� das Letras": "São Thomé das Letras",
  "S�o Tiago": "São Tiago",
  "S�o Tom�s de Aquino": "São Tomás de Aquino",
  "S�o Tom�": "São Tomé",
  "S�o Valentim": "São Valentim",
  "S�o Valentim do Sul": "São Valentim do Sul",
  "S�o Val�rio": "São Valério",
  "S�o Val�rio do Sul": "São Valério do Sul",
  "S�o Vendelino": "São Vendelino",
  "S�o Vicente": "São Vicente",
  "S�o Vicente de Minas": "São Vicente de Minas",
  "S�o Vicente do Serid�": "São Vicente do Seridó",
  "S�o Vicente do Sul": "São Vicente do Sul",
  "S�o Vicente Ferrer": "São Vicente Ferrer",
  "Sap�": "Sapé",
  "Sapea�u": "Sapeaçu",
  "Sapuca�-Mirim": "Sapucaí-Mirim",
  "Sarapu�": "Sarapuí",
  "Sardo�": "Sardoá",
  "Sarutai�": "Sarutaiá",
  "S�tiro Dias": "Sátiro Dias",
  "Saudade do Igua�u": "Saudade do Iguaçu",
  "Sa�de": "Saúde",
  "Sebastian�polis do Sul": "Sebastianópolis do Sul",
  "Sebasti�o Barros": "Sebastião Barros",
  "Sebasti�o Laranjeiras": "Sebastião Laranjeiras",
  "Sebasti�o Leal": "Sebastião Leal",
  "Selv�ria": "Selvíria",
  "Senador El�i de Souza": "Senador Elói de Souza",
  "Senador Jos� Bento": "Senador José Bento",
  "Senador Jos� Porf�rio": "Senador José Porfírio",
  "Senador Modestino Gon�alves": "Senador Modestino Gonçalves",
  "Senador S�": "Senador Sá",
  "Seng�s": "Sengés",
  "Senhora dos Rem�dios": "Senhora dos Remédios",
  "Sento S�": "Sento Sé",
  "Serafina Corr�a": "Serafina Corrêa",
  "S�rio": "Sério",
  "Serop�dica": "Seropédica",
  "Serra de S�o Bento": "Serra de São Bento",
  "Serra dos Aimor�s": "Serra dos Aimorés",
  "Serrano do Maranh�o": "Serrano do Maranhão",
  "Serran�polis": "Serranópolis",
  "Serran�polis de Minas": "Serranópolis de Minas",
  "Serran�polis do Igua�u": "Serranópolis do Iguaçu",
  "Serrol�ndia": "Serrolândia",
  "Sert�nia": "Sertânia",
  "Sertan�polis": "Sertanópolis",
  "Sert�o": "Sertão",
  "Sert�o Santana": "Sertão Santana",
  "Sert�ozinho": "Sertãozinho",
  "Sever�nia": "Severínia",
  "Sider�polis": "Siderópolis",
  "Sidrol�ndia": "Sidrolândia",
  "Silv�nia": "Silvânia",
  "Silvan�polis": "Silvanópolis",
  "Silveir�nia": "Silveirânia",
  "Silvian�polis": "Silvianópolis",
  "Sim�o Dias": "Simão Dias",
  "Sim�o Pereira": "Simão Pereira",
  "Sim�es": "Simões",
  "Sim�es Filho": "Simões Filho",
  "Simol�ndia": "Simolândia",
  "Simon�sia": "Simonésia",
  "Simpl�cio Mendes": "Simplício Mendes",
  "Sirinha�m": "Sirinhaém",
  "S�tio D'Abadia": "Sítio D'Abadia",
  "S�tio do Mato": "Sítio do Mato",
  "S�tio do Quinto": "Sítio do Quinto",
  "S�tio Novo": "Sítio Novo",
  "S�tio Novo do Tocantins": "Sítio Novo do Tocantins",
  "Sobr�lia": "Sobrália",
  "Socorro do Piau�": "Socorro do Piauí",
  "Sol�nea": "Solânea",
  "Solid�o": "Solidão",
  "Solon�pole": "Solonópole",
  "Soss�go": "Sossêgo",
  "Sucupira do Riach�o": "Sucupira do Riachão",
  "Sumar�": "Sumaré",
  "Sum�": "Sumé",
  "Suzan�polis": "Suzanápolis",
  "Taba�": "Tabaí",
  "Tabapor�": "Tabaporã",
  "Tabapu�": "Tabapuã",
  "Tabo�o da Serra": "Taboão da Serra",
  "Tacaimb�": "Tacaimbó",
  "Tagua�": "Taguaí",
  "Taia�u": "Taiaçu",
  "Tail�ndia": "Tailândia",
  "Tai�": "Taió",
  "Tai�va": "Taiúva",
  "Talism�": "Talismã",
  "Tamandar�": "Tamandaré",
  "Tamba�": "Tambaú",
  "Tamboril do Piau�": "Tamboril do Piauí",
  "Tangar�": "Tangará",
  "Tangar� da Serra": "Tangará da Serra",
  "Tangu�": "Tanguá",
  "Tanha�u": "Tanhaçu",
  "Tanque do Piau�": "Tanque do Piauí",
  "Tapau�": "Tapauá",
  "Tapero�": "Taperoá",
  "Tapira�": "Tapiraí",
  "Tapiramut�": "Tapiramutá",
  "Taquara�u de Minas": "Taquaraçu de Minas",
  "Taquaral de Goi�s": "Taquaral de Goiás",
  "Taquariva�": "Taquarivaí",
  "Taquaru�u do Sul": "Taquaruçu do Sul",
  "Tarauac�": "Tarauacá",
  "Tarum�": "Tarumã",
  "Tatu�": "Tatuí",
  "Tau�": "Tauá",
  "Taubat�": "Taubaté",
  "Tef�": "Tefé",
  "Teixeir�polis": "Teixeirópolis",
  "Teju�uoca": "Tejuçuoca",
  "Tejup�": "Tejupá",
  "Tel�maco Borba": "Telêmaco Borba",
  "Ten�rio": "Tenório",
  "Teofil�ndia": "Teofilândia",
  "Te�filo Otoni": "Teófilo Otoni",
  "Teol�ndia": "Teolândia",
  "Teot�nio Vilela": "Teotônio Vilela",
  "Teresina de Goi�s": "Teresina de Goiás",
  "Teres�polis": "Teresópolis",
  "Terez�polis de Goi�s": "Terezópolis de Goiás",
  "Teut�nia": "Teutônia",
  "Tiangu�": "Tianguá",
  "Tiet�": "Tietê",
  "Timba�ba": "Timbaúba",
  "Timba�ba dos Batistas": "Timbaúba dos Batistas",
  "Timb� do Sul": "Timbé do Sul",
  "Timb�": "Timbó",
  "Timb� Grande": "Timbó Grande",
  "Tim�teo": "Timóteo",
  "Tocant�nia": "Tocantínia",
  "Tocantin�polis": "Tocantinópolis",
  "Tom�-A�u": "Tomé-Açu",
  "Torixor�u": "Torixoréu",
  "Tracunha�m": "Tracunhaém",
  "Trair�o": "Trairão",
  "Tramanda�": "Tramandaí",
  "Trememb�": "Tremembé",
  "Tr�s Arroios": "Três Arroios",
  "Tr�s Barras": "Três Barras",
  "Tr�s Barras do Paran�": "Três Barras do Paraná",
  "Tr�s Cachoeiras": "Três Cachoeiras",
  "Tr�s Cora��es": "Três Corações",
  "Tr�s Coroas": "Três Coroas",
  "Tr�s de Maio": "Três de Maio",
  "Tr�s Forquilhas": "Três Forquilhas",
  "Tr�s Fronteiras": "Três Fronteiras",
  "Tr�s Lagoas": "Três Lagoas",
  "Tr�s Marias": "Três Marias",
  "Tr�s Palmeiras": "Três Palmeiras",
  "Tr�s Passos": "Três Passos",
  "Tr�s Pontas": "Três Pontas",
  "Tr�s Ranchos": "Três Ranchos",
  "Tr�s Rios": "Três Rios",
  "Treze T�lias": "Treze Tílias",
  "Tubar�o": "Tubarão",
  "Tucum�": "Tucumã",
  "Tucuru�": "Tucuruí",
  "Tufil�ndia": "Tufilândia",
  "Tun�polis": "Tunápolis",
  "Tunas do Paran�": "Tunas do Paraná",
  "Tup�": "Tupã",
  "Tupanciret�": "Tupanciretã",
  "Tup�ssi": "Tupãssi",
  "Turia�u": "Turiaçu",
  "Turil�ndia": "Turilândia",
  "Turi�ba": "Turiúba",
  "Turu�u": "Turuçu",
  "Turv�nia": "Turvânia",
  "Turvel�ndia": "Turvelândia",
  "Turvol�ndia": "Turvolândia",
  "Tut�ia": "Tutóia",
  "Uau�": "Uauá",
  "Ub�": "Ubá",
  "Uba�": "Ubaí",
  "Uba�ra": "Ubaíra",
  "Ubat�": "Ubatã",
  "Uberl�ndia": "Uberlândia",
  "Ubirat�": "Ubiratã",
  "Uiba�": "Uibaí",
  "Uiramut�": "Uiramutã",
  "Uira�na": "Uiraúna",
  "Ulian�polis": "Ulianópolis",
  "Umba�ba": "Umbaúba",
  "Una�": "Unaí",
  "Uni�o": "União",
  "Uni�o da Serra": "União da Serra",
  "Uni�o da Vit�ria": "União da Vitória",
  "Uni�o de Minas": "União de Minas",
  "Uni�o do Oeste": "União do Oeste",
  "Uni�o do Sul": "União do Sul",
  "Uni�o dos Palmares": "União dos Palmares",
  "Uni�o Paulista": "União Paulista",
  "Ura�": "Uraí",
  "Ur�nia": "Urânia",
  "Urua�u": "Uruaçu",
  "Uruar�": "Uruará",
  "Uruc�nia": "Urucânia",
  "Urucar�": "Urucará",
  "Uru�uca": "Uruçuca",
  "Uru�u�": "Uruçuí",
  "Urup�": "Urupá",
  "Urup�s": "Urupês",
  "Uruta�": "Urutaí",
  "Vale de S�o Domingos": "Vale de São Domingos",
  "Vale do Para�so": "Vale do Paraíso",
  "Valen�a": "Valença",
  "Valen�a do Piau�": "Valença do Piauí",
  "Valpara�so": "Valparaíso",
  "Valpara�so de Goi�s": "Valparaíso de Goiás",
  "Varge�o": "Vargeão",
  "Varj�o": "Varjão",
  "Varj�o de Minas": "Varjão de Minas",
  "V�rzea": "Várzea",
  "V�rzea Alegre": "Várzea Alegre",
  "V�rzea Branca": "Várzea Branca",
  "V�rzea da Palma": "Várzea da Palma",
  "V�rzea da Ro�a": "Várzea da Roça",
  "V�rzea do Po�o": "Várzea do Poço",
  "V�rzea Grande": "Várzea Grande",
  "V�rzea Nova": "Várzea Nova",
  "V�rzea Paulista": "Várzea Paulista",
  "Varzel�ndia": "Varzelândia",
  "Ven�ncio Aires": "Venâncio Aires",
  "Veran�polis": "Veranópolis",
  "Verdel�ndia": "Verdelândia",
  "Ver�": "Verê",
  "Ver�ssimo": "Veríssimo",
  "Vertente do L�rio": "Vertente do Lério",
  "Viam�o": "Viamão",
  "Vian�polis": "Vianópolis",
  "Vic�ncia": "Vicência",
  "Vicentin�polis": "Vicentinópolis",
  "Vi�osa": "Viçosa",
  "Vi�osa do Cear�": "Viçosa do Ceará",
  "Vieir�polis": "Vieirópolis",
  "Vila Bela da Sant�ssima Trindade": "Vila Bela da Santíssima Trindade",
  "Vila L�ngaro": "Vila Lângaro",
  "Vila Nova do Piau�": "Vila Nova do Piauí",
  "Vila Nova dos Mart�rios": "Vila Nova dos Martírios",
  "Vila Pav�o": "Vila Pavão",
  "Vila Prop�cio": "Vila Propício",
  "Vila Val�rio": "Vila Valério",
  "Virg�nia": "Virgínia",
  "Virgin�polis": "Virginópolis",
  "Virgol�ndia": "Virgolândia",
  "Vista Ga�cha": "Vista Gaúcha",
  "Vit�ria": "Vitória",
  "Vit�ria Brasil": "Vitória Brasil",
  "Vit�ria da Conquista": "Vitória da Conquista",
  "Vit�ria das Miss�es": "Vitória das Missões",
  "Vit�ria de Santo Ant�o": "Vitória de Santo Antão",
  "Vit�ria do Jari": "Vitória do Jari",
  "Vit�ria do Mearim": "Vitória do Mearim",
  "Vit�ria do Xingu": "Vitória do Xingu",
  "Wanderl�ndia": "Wanderlândia",
  "Wenceslau Guimar�es": "Wenceslau Guimarães",
  "Westf�lia": "Westfália",
  "Xambio�": "Xambioá",
  "Xambr�": "Xambrê",
  "Xangri-L�": "Xangri-Lá",
  "Xanxer�": "Xanxerê",
  "Xex�u": "Xexéu",
  "Zabel�": "Zabelê",
  "Z� Doca": "Zé Doca",
  "Zort�a": "Zortéa",
};
